// Generated by scripts/glossary_build.py; edit docs/typst/shared/glossary.typ.
// Compatibility aliases read canonical entries at Typst evaluation time;
// this file intentionally owns no labels, abbreviations, or definitions.

#import "glossary.typ": aria-glossary-entries

#let _canonical-term(key) = aria-glossary-entries.find(entry => entry.key == key)
#let _canonical-short(key) = {
  let term = _canonical-term(key)
  if term.short == none { term.long } else { term.short }
}
#let _canonical-long(key) = _canonical-term(key).long

// Temporary compatibility constants. New prose uses Glossarium-native
// @term references and does not import this facade.
#let ADT = _canonical-short("aria-digital-twin")
#let ADT_full = _canonical-long("aria-digital-twin")
#let AEO = _canonical-short("aria-everyday-objects")
#let AEO_full = _canonical-long("aria-everyday-objects")
#let ASE = _canonical-short("aria-synthetic-environments")
#let ASE_full = _canonical-long("aria-synthetic-environments")
#let AUC = _canonical-short("area-under-curve")
#let AUC_full = _canonical-long("area-under-curve")
#let CD = _canonical-short("chamfer-distance")
#let CD_full = _canonical-long("chamfer-distance")
#let CR = _canonical-short("coverage-ratio")
#let CR_full = _canonical-long("coverage-ratio")
#let DoF = _canonical-short("degrees-of-freedom")
#let DoF_full = _canonical-long("degrees-of-freedom")
#let EFM3D = _canonical-short("egocentric-foundation-model-3d")
#let EFM3D_full = _canonical-long("egocentric-foundation-model-3d")
#let EVL = _canonical-short("egocentric-voxel-lifting")
#let EVL_full = _canonical-long("egocentric-voxel-lifting")
#let FiveDoF = _canonical-short("five-degrees-of-freedom")
#let FiveDoF_full = _canonical-long("five-degrees-of-freedom")
#let GT = _canonical-short("ground-truth")
#let GT_full = _canonical-long("ground-truth")
#let MVS = _canonical-short("multi-view-stereo")
#let MVS_full = _canonical-long("multi-view-stereo")
#let NBV = _canonical-short("next-best-view")
#let NBV_full = _canonical-long("next-best-view")
#let OccGrid = _canonical-short("occupancy-grid")
#let OccGrid_full = _canonical-long("occupancy-grid")
#let PC = _canonical-short("point-cloud")
#let PC_full = _canonical-long("point-cloud")
#let RRI = _canonical-short("relative-reconstruction-improvement")
#let RRI_full = _canonical-long("relative-reconstruction-improvement")
#let SixDoF = _canonical-short("six-degrees-of-freedom")
#let SixDoF_full = _canonical-long("six-degrees-of-freedom")
#let SLAM = _canonical-short("simultaneous-localization-and-mapping")
#let SLAM_full = _canonical-long("simultaneous-localization-and-mapping")
#let SSL = _canonical-short("scene-script-language")
#let SSL_full = _canonical-long("scene-script-language")
