// Canonical ARIA-NBV glossary source.
// Humans edit this file; `make glossary` regenerates Quarto, Typst, YAML, and KG artifacts.

#import "@preview/glossarium:0.5.10": make-glossary, print-glossary, register-glossary
#import "symbols.typ": symb
#import "equations.typ": eqs

// Rich `description` fields may use Typst content, including #symb and #eqs.
// Keep `custom` fields machine-readable so `typst query` can feed generated docs.
#let aria-glossary-entries = (
  (
    key: "next-best-view",
    short: "NBV",
    long: "Next-Best-View",
    description: "Problem of selecting the next sensor viewpoint to improve an active reconstruction or inspection objective under a limited acquisition budget. In ARIA-NBV, the preferred objective is reconstruction quality improvement rather than coverage alone, with candidate views ranked by oracle or learned RRI scores.",
    group: "Planning",
    custom: (
      anchor: "term-next-best-view",
      aliases: (
        "next best view",
        "viewpoint selection",
        "view planning",
      ),
      category: "planning.view_selection",
      parent: "view-planning",
      definition_short: "Problem of selecting the next sensor viewpoint to improve an active reconstruction or inspection objective under a limited acquisition budget.",
      definition_long: "In ARIA-NBV, the preferred objective is reconstruction quality improvement rather than coverage alone, with candidate views ranked by oracle or learned RRI scores.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
        "docs/contents/thesis/roadmap.qmd",
        "docs/contents/thesis/questions.qmd#research-questions",
      ),
      citations: (
        "VIN-NBV-frahm2025",
        "GenNBV-chen2024",
      ),
      related: (
        "candidate-view",
        "relative-reconstruction-improvement",
        "view-introspection-network",
      ),
      kg_tags: (
        "planning",
        "active-reconstruction",
      ),
      tier: "core",
      lookup_rank: 10,
      symbol_refs: (
        "rl.mdp_nbv",
      ),
      equation_refs: (
        "rl.nbv_mdp",
      ),
      typst_macro: "NBV",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "relative-reconstruction-improvement",
    short: "RRI",
    long: "Relative Reconstruction Improvement",
    description: "Metric quantifying the relative reconstruction-quality improvement obtained by adding a candidate observation to the current reconstruction. ARIA-NBV computes RRI by comparing reconstruction error before and after fusing candidate-view geometry, usually against an ASE ground-truth mesh for oracle supervision and evaluation.",
    group: "Metrics",
    custom: (
      anchor: "term-relative-reconstruction-improvement",
      aliases: (
        "reconstruction-quality gain",
        "relative quality improvement",
      ),
      category: "metrics.reconstruction_quality",
      parent: "reconstruction-quality",
      definition_short: "Metric quantifying the relative reconstruction-quality improvement obtained by adding a candidate observation to the current reconstruction.",
      definition_long: "ARIA-NBV computes RRI by comparing reconstruction error before and after fusing candidate-view geometry, usually against an ASE ground-truth mesh for oracle supervision and evaluation.",
      internal_links: (
        "docs/contents/theory/rri_theory.qmd",
        "docs/reference/oracle.scene_rri.qmd",
        "docs/contents/literature/vin_nbv.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "oracle-rri",
        "target-specific-rri",
        "candidate-view",
      ),
      kg_tags: (
        "metric",
        "oracle-label",
        "reconstruction-quality",
      ),
      tier: "core",
      lookup_rank: 20,
      symbol_refs: (
        "oracle.rri",
      ),
      equation_refs: (
        "rri.rri",
      ),
      typst_macro: "RRI",
      notation: (
        typst: "#symb.oracle.rri",
      ),
      formula: (
        tex: "\\mathrm{RRI}(q)=\\frac{D(\\mathcal{P}_t,\\mathcal{M}^{\\mathrm{GT}})-D(\\mathcal{P}_t\\cup\\mathcal{P}_q,\\mathcal{M}^{\\mathrm{GT}})}{D(\\mathcal{P}_t,\\mathcal{M}^{\\mathrm{GT}})+\\varepsilon}",
        typst: "$op(\"RRI\") (q) = (#(symb.oracle.err) (#(symb.oracle.points)_t, #(symb.ase.mesh)) - #(symb.oracle.err) (#(symb.oracle.points)_t union #(symb.oracle.points_q), #(symb.ase.mesh))) / (#(symb.oracle.err) (#(symb.oracle.points)_t, #(symb.ase.mesh)) + epsilon)$",
      ),
      formulae: (),
    ),
  ),
  (
    key: "ground-truth",
    short: "GT",
    long: "Ground Truth",
    description: "Reference data or annotations treated as the trusted target for training, validation, or evaluation. In ARIA-NBV, ground truth usually refers to ASE meshes, object annotations, poses, or labels used to compute oracle supervision and diagnostic metrics.",
    group: "Metrics",
    custom: (
      anchor: "term-ground-truth",
      aliases: (
        "reference annotation",
        "oracle reference",
      ),
      category: "metrics.reference",
      parent: "supervision",
      definition_short: "Reference data or annotations treated as the trusted target for training, validation, or evaluation.",
      definition_long: "In ARIA-NBV, ground truth usually refers to ASE meshes, object annotations, poses, or labels used to compute oracle supervision and diagnostic metrics.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "oracle-rri",
        "relative-reconstruction-improvement",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "supervision",
        "evaluation",
        "ground-truth",
      ),
      tier: "support",
      typst_macro: "GT",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-of-interest",
    short: "target",
    long: "Target of Interest",
    description: "Selected entity, object crop, point, region, or surface-deficit hypothesis whose reconstruction quality should be improved. Target-conditioned ARIA-NBV variants use this target as an explicit input to candidate scoring and planning instead of optimizing only scene-level RRI.",
    group: "Entity",
    custom: (
      anchor: "term-target-of-interest",
      aliases: (
        "target entity",
        "object of interest",
        "inspection target",
        "task target",
      ),
      category: "entity.targeting",
      parent: "entity-aware-rri",
      definition_short: "Selected entity, object crop, point, region, or surface-deficit hypothesis whose reconstruction quality should be improved.",
      definition_long: "Target-conditioned ARIA-NBV variants use this target as an explicit input to candidate scoring and planning instead of optimizing only scene-level RRI.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/reference/vin.types.qmd",
      ),
      citations: (),
      related: (
        "target-specific-rri",
        "target-conditioned-scorer",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "entity-aware",
        "target-conditioned",
      ),
      tier: "core",
      lookup_rank: 40,
      symbol_refs: (
        "rl.target",
        "ase.mesh_target",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-specific-rri",
    short: "target RRI",
    long: "Target-Specific RRI",
    description: "RRI computed only on the ground-truth and reconstructed geometry associated with a selected target of interest. Target-specific RRI lets the thesis compare views by how much they improve a selected object or region, even when scene-level RRI would prefer large background surfaces.",
    group: "Metrics",
    custom: (
      anchor: "term-target-specific-rri",
      aliases: (
        "entity RRI",
        "object RRI",
        "target RRI",
      ),
      category: "metrics.reconstruction_quality",
      parent: "relative-reconstruction-improvement",
      definition_short: "RRI computed only on the ground-truth and reconstructed geometry associated with a selected target of interest.",
      definition_long: "Target-specific RRI lets the thesis compare views by how much they improve a selected object or region, even when scene-level RRI would prefer large background surfaces.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq1-objective",
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "target-of-interest",
        "acquisition-cost",
      ),
      kg_tags: (
        "metric",
        "entity-aware",
        "thesis-core",
      ),
      tier: "core",
      lookup_rank: 30,
      symbol_refs: (
        "entity.rri_e",
        "ase.mesh_target",
      ),
      equation_refs: (
        "rri.target_rri",
      ),
      typst_macro: none,
      notation: (
        typst: "$RRI_e$",
      ),
      formula: (
        tex: "\\mathrm{RRI}_e(q)=\\frac{D(\\mathcal{P}_t^e,\\mathcal{M}_e^{\\mathrm{GT}})-D(\\mathcal{P}_t^e\\cup\\mathcal{P}_q^e,\\mathcal{M}_e^{\\mathrm{GT}})}{D(\\mathcal{P}_t^e,\\mathcal{M}_e^{\\mathrm{GT}})+\\varepsilon}",
        typst: "$op(\"RRI\")_e (q) = (#(symb.oracle.err) (#(symb.oracle.points)_t^e, #(symb.ase.mesh_target)) - #(symb.oracle.err) (#(symb.oracle.points)_t^e union #(symb.oracle.points)_q^e, #(symb.ase.mesh_target))) / (#(symb.oracle.err) (#(symb.oracle.points)_t^e, #(symb.ase.mesh_target)) + epsilon)$",
      ),
      formulae: (),
    ),
  ),
  (
    key: "acquisition-cost",
    short: "cost",
    long: "Acquisition Cost",
    description: "Budget consumed to acquire observations, measured by view count, path length, elapsed time, invalid-action rate, or a weighted combination. The thesis should first report cumulative root-normalized target gain, diagnostic target RRI, and acquisition cost separately, then use scalarized objectives only when the tradeoff is explicit.",
    group: "Planning",
    custom: (
      anchor: "term-acquisition-cost",
      aliases: (
        "capture budget",
        "view budget",
        "motion cost",
      ),
      category: "planning.objective",
      parent: "trajectory-objective",
      definition_short: "Budget consumed to acquire observations, measured by view count, path length, elapsed time, invalid-action rate, or a weighted combination.",
      definition_long: "The thesis should first report cumulative root-normalized target gain, diagnostic target RRI, and acquisition cost separately, then use scalarized objectives only when the tradeoff is explicit.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq1-objective",
        "docs/contents/thesis/roadmap.qmd#roadmap-m5",
      ),
      citations: (),
      related: (
        "target-specific-rri",
        "candidate-view",
        "next-best-view",
      ),
      kg_tags: (
        "objective",
        "planning",
        "evaluation",
      ),
      tier: "core",
      lookup_rank: 120,
      symbol_refs: (
        "rl.acquisition_cost",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-conditioned-scorer",
    short: "target-conditioned scorer",
    long: "Target-Conditioned Scorer",
    description: "VIN-style candidate scorer that receives scene state, a candidate view, and an encoding of the target of interest. The scorer predicts target-specific utility so view ranking can prioritize a selected entity or region instead of only optimizing scene-level RRI.",
    group: "Model",
    custom: (
      anchor: "term-target-conditioned-scorer",
      aliases: (
        "target-conditioned VIN",
        "target-aware scorer",
      ),
      category: "model.scoring",
      parent: "view-introspection-network",
      definition_short: "VIN-style candidate scorer that receives scene state, a candidate view, and an encoding of the target of interest.",
      definition_long: "The scorer predicts target-specific utility so view ranking can prioritize a selected entity or region instead of only optimizing scene-level RRI.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/reference/vin.models.scene_myopic.qmd",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "target-of-interest",
        "target-specific-rri",
        "view-introspection-network",
        "finite-horizon-q-function",
      ),
      kg_tags: (
        "model",
        "target-conditioned",
        "vin",
      ),
      tier: "core",
      lookup_rank: 90,
      symbol_refs: (
        "vin.rri_hat",
      ),
      equation_refs: (
        "metrics.spearman",
        "metrics.topk_acc",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "observed-target-selection",
    short: "OBS-SEL",
    long: "Observed Target Selection",
    description: "Main thesis protocol component requiring target selection to use only actor-visible evidence such as predicted or tracked OBBs, class probabilities, confidence, projected area, and semidense or EVL support. Ground-truth target annotations are not visible to the selector in this protocol.",
    group: "Protocol",
    custom: (
      anchor: "term-observed-target-selection",
      aliases: (
        "observed-only target selection",
        "actor-visible target selection",
      ),
      category: "protocol.targeting",
      parent: "target-of-interest",
      definition_short: "Main thesis protocol component requiring target selection to use only actor-visible observed or predicted target evidence.",
      definition_long: "Observed Target Selection uses predicted or tracked OBBs, class probabilities, confidence, projected area, and semidense or EVL support. Ground-truth target annotations are not visible to the selector in the main thesis protocol.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/contents/thesis/questions.qmd#rq-thesis-boundary",
      ),
      citations: (
        "EFM3D-straub2024",
        "ProjectAria-ASE-2025",
      ),
      related: (
        "target-of-interest",
        "predicted-target-q",
        "ground-truth-target-evaluation",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "protocol",
        "target-conditioned",
        "actor-visible",
      ),
      tier: "core",
      lookup_rank: 100,
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "predicted-target-q",
    short: "PRED-Q",
    long: "Predicted-Target Q",
    description: [
      Main thesis protocol component requiring the scorer or fitted #symb.rl.qh model to condition on predicted or observed target descriptors rather than ground-truth target inputs. It covers target-conditioned one-step scoring and finite-candidate #symb.rl.qh selection.
    ],
    group: "Protocol",
    custom: (
      anchor: "term-predicted-target-q",
      aliases: (
        "predicted-target scorer",
        "predicted-target Q_H",
        "actor-visible Q",
      ),
      category: "protocol.learning",
      parent: "target-conditioned-scorer",
      definition_short: "Main thesis protocol component requiring scorer or Q_H inputs to use predicted or observed target descriptors.",
      definition_long: "Predicted-Target Q covers target-conditioned one-step scoring and finite-candidate Q_H selection whose target inputs are actor-visible predicted or observed descriptors, not ground-truth target annotations.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/contents/thesis/questions.qmd#rq4-planning",
      ),
      citations: (
        "VIN-NBV-frahm2025",
        "DoubleDQN-vanHasselt2015",
      ),
      related: (
        "observed-target-selection",
        "ground-truth-target-evaluation",
        "target-conditioned-scorer",
        "target-specific-rri",
        "finite-horizon-q-function",
      ),
      kg_tags: (
        "protocol",
        "q-learning",
        "target-conditioned",
      ),
      tier: "core",
      lookup_rank: 110,
      symbol_refs: (
        "rl.qh",
      ),
      equation_refs: (
        "rl.q_h",
      ),
      typst_macro: none,
      notation: (
        typst: "$Q_H$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "ground-truth-target-evaluation",
    short: "GT-EVAL",
    long: "Ground-Truth Target Evaluation",
    description: "Main thesis protocol component restricting ground-truth OBBs and target mesh crops to oracle labels, target-RRI computation, matching checks, and evaluation. GT target crops are not actor-visible inputs in the main result.",
    group: "Protocol",
    custom: (
      anchor: "term-ground-truth-target-evaluation",
      aliases: (
        "GT target evaluation",
        "GT target crop evaluation",
        "oracle target evaluation",
      ),
      category: "protocol.evaluation",
      parent: "ground-truth",
      definition_short: "Main thesis protocol component using ground-truth OBBs and target mesh crops only for labels and evaluation.",
      definition_long: "Ground-Truth Target Evaluation uses GT OBBs and target mesh crops for oracle target-RRI labels, matching checks, and evaluation while keeping those annotations hidden from the actor-visible selector, scorer, and Q_H model in the main result.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/contents/thesis/questions.qmd#rq1-objective",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "ground-truth",
        "target-specific-rri",
        "observed-target-selection",
        "predicted-target-q",
      ),
      kg_tags: (
        "protocol",
        "oracle-label",
        "evaluation",
      ),
      tier: "core",
      lookup_rank: 115,
      symbol_refs: (
        "ase.mesh_target",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "target-conditioned-nbv-mdp",
    short: "NBV MDP",
    long: "Target-Conditioned NBV MDP",
    description: [
      Finite-horizon Markov decision process used to define ARIA-NBV's target-conditioned rollout and fitted #symb.rl.qh training contract. The actor observes only current reconstruction state, sampled candidate views, validity masks, target descriptors, history, and budget state; oracle meshes and GT crops are supervision and evaluation signals.
    ],
    group: "Planning",
    custom: (
      anchor: "term-target-conditioned-nbv-mdp",
      aliases: (
        "ARIA-NBV MDP",
        "rollout MDP",
        "finite-candidate NBV MDP",
      ),
      category: "planning.mdp",
      parent: "next-best-view",
      definition_short: "Finite-horizon MDP contract for target-conditioned ARIA-NBV rollouts and fitted Q_H training.",
      definition_long: "The ARIA-NBV MDP keeps actions restricted to sampled finite candidate views and keeps GT meshes or GT target crops outside the actor-visible state. It is the contract that connects target-conditioned rollout generation, reward computation, validity masks, and fitted finite-horizon Q learning.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#rl-planning-theory",
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/contents/thesis/roadmap.qmd#roadmap-m5",
      ),
      citations: (
        "VIN-NBV-frahm2025",
        "DoubleDQN-vanHasselt2015",
      ),
      related: (
        "rollout-state",
        "finite-candidate-action-set",
        "counterfactual-transition",
        "target-rri-reward",
        "finite-horizon-return",
        "finite-horizon-q-function",
        "validity-mask",
      ),
      kg_tags: (
        "planning",
        "mdp",
        "thesis-core",
      ),
      tier: "core",
      lookup_rank: 130,
      symbol_refs: (
        "rl.mdp_nbv",
        "rl.s",
        "rl.action_set",
        "rl.transition",
        "rl.reward_target",
        "rl.gamma",
        "rl.H",
      ),
      equation_refs: (
        "rl.nbv_mdp",
      ),
      typst_macro: none,
      notation: (
        typst: "$cal(M)_(\"NBV\")$",
      ),
      formula: (
        label: "ARIA-NBV MDP contract",
        tex: "\\mathcal{M}_{\\mathrm{NBV}}=(\\mathcal{S},\\mathcal{A},T,r_e,\\gamma,H)",
      ),
      formulae: (),
    ),
  ),
  (
    key: "rollout-state",
    short: "state",
    long: "Rollout State",
    description: "Family of rollout state variants used by ARIA-NBV. The actor-visible variants contain logged or replayed observations, reconstruction proxies, candidates, validity masks, target descriptors, history, and budget; the oracle variant adds privileged GT geometry and all-candidate labels for supervision and evaluation only.",
    group: "Planning",
    custom: (
      anchor: "term-rollout-state",
      aliases: (
        "MDP state",
        "actor-visible state",
        "rollout observation",
      ),
      category: "planning.mdp",
      parent: "target-conditioned-nbv-mdp",
      definition_short: "Rollout state family separating actor-visible state from oracle-only supervision.",
      definition_long: "ARIA-NBV distinguishes raw historic snippet state, persisted VIN offline sample state, minimal counterfactual actor state, geometry-rich counterfactual ablation state, and privileged oracle rollout state. The main Q_H actor input starts from the minimal counterfactual state; all-candidate GT renders, GT mesh crops, and oracle RRI labels remain outside the actor-visible state.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#state-and-action-space-contract",
        "docs/contents/thesis/questions.qmd#rq4-planning",
      ),
      citations: (),
      related: (
        "historic-snippet-state",
        "persisted-offline-state",
        "minimal-counterfactual-state",
        "geometry-rich-counterfactual-state",
        "oracle-rollout-state",
        "finite-candidate-action-set",
        "validity-mask",
        "observed-target-selection",
        "predicted-target-q",
      ),
      kg_tags: (
        "planning",
        "state",
        "actor-visible",
      ),
      tier: "core",
      lookup_rank: 140,
      symbol_refs: (
        "rl.s",
        "rl.s_hist",
        "rl.s_off",
        "rl.s_cf0",
        "rl.s_cf_geom",
        "rl.s_oracle",
        "oracle.points",
        "oracle.candidates_t",
        "rl.validity_mask",
        "rl.invalid_reason",
        "rl.target",
        "rl.budget",
      ),
      equation_refs: (
        "rl.s_hist",
        "rl.s_off",
        "rl.s_cf0",
        "rl.s_cf_geom",
        "rl.s_oracle",
      ),
      typst_macro: none,
      notation: (
        typst: "$s_t$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "historic-snippet-state",
    short: "historic state",
    long: "Historic Snippet State",
    description: "Raw actor-visible state available along the logged Project Aria/ASE trajectory before counterfactual rollout synthesis. It includes captured camera streams, calibration, timestamps, trajectory/gravity, semidense points with support or uncertainty, EVL/EFM evidence, and detected or predicted OBBs; GT mesh and GT OBBs are excluded as actor inputs.",
    group: "Planning",
    custom: (
      anchor: "term-historic-snippet-state",
      aliases: (
        "raw historic state",
        "logged snippet state",
        "historic observed state",
      ),
      category: "planning.state",
      parent: "rollout-state",
      definition_short: "Raw actor-visible state from the logged ASE/Project Aria snippet trajectory.",
      definition_long: "The historic snippet state is the richest non-privileged state because it comes from the original logged trajectory. It may contain calibrated camera streams, timestamps, trajectory and gravity estimates, semidense points with support fields, frozen EVL/EFM evidence, and observed or predicted OBBs. It must not contain the GT mesh or GT OBB crops as actor inputs.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#state-and-action-space-contract",
        "docs/contents/literature/project_aria.qmd",
        "docs/contents/literature/efm3d.qmd",
      ),
      citations: (
        "projectaria-engel2023",
        "EFM3D-straub2024",
      ),
      related: (
        "persisted-offline-state",
        "egocentric-voxel-lifting",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "planning",
        "state",
        "historic",
      ),
      tier: "core",
      lookup_rank: 141,
      symbol_refs: (
        "rl.s_hist",
      ),
      equation_refs: (
        "rl.s_hist",
      ),
      typst_macro: none,
      notation: (
        typst: "$s_t^\"hist\"$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "persisted-offline-state",
    short: "offline state",
    long: "Persisted Offline Sample State",
    description: "Compact VIN offline-store state persisted for training and diagnostics. It contains the VinSnippetView payload, candidate table and cameras, candidate count, validity or count metadata, oracle metrics as labels, optional rendered depths, compact OBBs, trajectory metadata, and selected EVL numeric fields.",
    group: "Planning",
    custom: (
      anchor: "term-persisted-offline-state",
      aliases: (
        "offline sample state",
        "VIN offline state",
        "persisted VIN state",
      ),
      category: "planning.state",
      parent: "rollout-state",
      definition_short: "Compact persisted state used by VIN training and offline diagnostics.",
      definition_long: "The persisted offline sample state is not the full raw snippet. It is the compact immutable training and diagnostic payload: VinSnippetView, candidate poses/cameras/counts, labels and oracle metrics, optional candidate depths, compact OBB fields, trajectory metadata, and selected EVL numeric tensors needed to reproduce scoring diagnostics.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#state-and-action-space-contract",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
      ),
      citations: (),
      related: (
        "historic-snippet-state",
        "vin-nbv",
        "oracle-rri",
      ),
      kg_tags: (
        "planning",
        "offline-store",
        "vin",
      ),
      tier: "core",
      lookup_rank: 142,
      symbol_refs: (
        "rl.s_off",
      ),
      equation_refs: (
        "rl.s_off",
      ),
      typst_macro: none,
      notation: (
        typst: "$s_t^\"off\"$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "minimal-counterfactual-state",
    short: "CF0 state",
    long: "Minimal Counterfactual Actor State",
    description: [
      Main thesis-core actor-visible counterfactual rollout state. It keeps the fused point proxy #symb.obs.points_t as broad scene state, optional lifted image-foundation features attached to points, local root EVL evidence for target support, selected-view history, target descriptor, budget, candidate table, validity masks and reason codes, and current candidate-query features, without exposing all-candidate GT renders.
    ],
    group: "Planning",
    custom: (
      anchor: "term-minimal-counterfactual-state",
      aliases: (
        "minimal counterfactual state",
        "counterfactual actor state",
        "CF0 rollout state",
      ),
      category: "planning.state",
      parent: "rollout-state",
      definition_short: "Main Q_H actor state for mesh-supervised counterfactual rollouts.",
      definition_long: "The minimal counterfactual actor state is the default input to target-conditioned Q_H. It contains the accumulated counterfactual point proxy as broad scene state, optional lifted image-foundation point features, local root EVL evidence for target support and local reads, selected-action history, observed or predicted target descriptor, budget state, finite candidate table, validity masks, reason codes, and current-state candidate-query features. Synthetic observations update the state only after their candidate is selected.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#state-and-action-space-contract",
        "docs/contents/theory/efm3d_scene_embeddings.qmd",
        "docs/contents/thesis/questions.qmd#rq4-planning",
      ),
      citations: (),
      related: (
        "geometry-rich-counterfactual-state",
        "finite-candidate-action-set",
        "counterfactual-transition",
        "finite-horizon-q-function",
      ),
      kg_tags: (
        "planning",
        "counterfactual",
        "actor-visible",
      ),
      tier: "core",
      lookup_rank: 143,
      symbol_refs: (
        "rl.s_cf0",
      ),
      equation_refs: (
        "rl.s_cf0",
      ),
      typst_macro: none,
      notation: (
        typst: "$s_t^\"cf0\"$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "geometry-rich-counterfactual-state",
    short: "CF+ state",
    long: "Geometry-Rich Counterfactual State",
    description: "Ablation actor state that extends the minimal counterfactual state with selected prior synthetic observations only: rendered depth, valid mask, backprojected point cloud, and derived local normals or support summaries.",
    group: "Planning",
    custom: (
      anchor: "term-geometry-rich-counterfactual-state",
      aliases: (
        "geometry-rich counterfactual state",
        "counterfactual geometry state",
        "CF+ rollout state",
      ),
      category: "planning.state",
      parent: "rollout-state",
      definition_short: "Counterfactual ablation state with selected synthetic geometry observations.",
      definition_long: "The geometry-rich counterfactual state adds only selected prior synthetic observations to the minimal state. It may include rendered depth, depth-valid masks, backprojected points, derived normals, and local support summaries for views that have already been selected. It does not include oracle renders for unselected candidates.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#state-and-action-space-contract",
        "docs/contents/thesis/questions.qmd#rq4-planning",
      ),
      citations: (),
      related: (
        "minimal-counterfactual-state",
        "counterfactual-transition",
        "oracle-rollout-state",
      ),
      kg_tags: (
        "planning",
        "counterfactual",
        "geometry",
      ),
      tier: "core",
      lookup_rank: 144,
      symbol_refs: (
        "rl.s_cf_geom",
      ),
      equation_refs: (
        "rl.s_cf_geom",
      ),
      typst_macro: none,
      notation: (
        typst: "$s_t^\"cf+\"$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "oracle-rollout-state",
    short: "oracle state",
    long: "Oracle Rollout State",
    description: "Privileged state used only for ASE mesh-supervised label generation, upper-bound planning, and evaluation. It includes GT mesh and target crops, all-candidate renders, points, normals, mesh-face visibility, RRI and point-mesh error metrics, oracle scores, and GT OBBs.",
    group: "Planning",
    custom: (
      anchor: "term-oracle-rollout-state",
      aliases: (
        "oracle state",
        "privileged rollout state",
        "GT rollout state",
      ),
      category: "planning.state",
      parent: "rollout-state",
      definition_short: "Privileged rollout state for labels, upper bounds, and evaluation.",
      definition_long: "The oracle rollout state may contain GT mesh geometry, GT target crops, GT OBBs, all-candidate synthetic depth and point clouds, derived normals, mesh-face visibility, Chamfer/RRI terms, and oracle scores. These fields support label generation and diagnostics but are not actor-visible inputs for the main scorer or Q_H model.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#state-and-action-space-contract",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "ground-truth-target-evaluation",
        "oracle-rri",
        "target-specific-rri",
        "minimal-counterfactual-state",
      ),
      kg_tags: (
        "planning",
        "oracle",
        "supervision",
      ),
      tier: "core",
      lookup_rank: 145,
      symbol_refs: (
        "rl.s_oracle",
      ),
      equation_refs: (
        "rl.s_oracle",
      ),
      typst_macro: none,
      notation: (
        typst: "$s_t^\"oracle\"$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "finite-candidate-action-set",
    short: "action set",
    long: "Finite Candidate Action Set",
    description: [
      Valid discrete action set for ARIA-NBV planning, obtained by masking a sampled candidate view table. The action is the candidate-table index, not a continuous pose; the selected pose is $q_t = q_(t,a_t)$. Invalid candidates are constraints, not low-quality actions.
    ],
    group: "Planning",
    custom: (
      anchor: "term-finite-candidate-action-set",
      aliases: (
        "candidate action set",
        "masked candidate set",
        "finite NBV action space",
      ),
      category: "planning.mdp",
      parent: "target-conditioned-nbv-mdp",
      definition_short: "Masked finite action-index set over sampled candidate views.",
      definition_long: "At each rollout step, ARIA-NBV samples a finite candidate table Q_t={q_{t,i}}. The admissible action set contains indices i whose validity mask m_{t,i} is true, and selecting a_t chooses pose q_t=q_{t,a_t}. This keeps planning bounded and preserves invalidity as a feasibility constraint rather than a low-quality RRI label.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq3-candidates",
        "docs/contents/theory/rl_planning.qmd#rl-planning-theory",
        "docs/reference/aria_nbv.pose_generation.CandidateViewGenerator.qmd",
      ),
      citations: (),
      related: (
        "candidate-view",
        "validity-mask",
        "rollout-state",
      ),
      kg_tags: (
        "planning",
        "candidate-view",
        "action-space",
      ),
      tier: "core",
      lookup_rank: 150,
      symbol_refs: (
        "rl.action_set",
        "oracle.candidate_qti",
        "oracle.candidates_t",
        "rl.validity_mask",
      ),
      equation_refs: (
        "rl.finite_action_set",
      ),
      typst_macro: none,
      notation: (
        typst: "$cal(A)(s_t)$",
      ),
      formula: (
        label: "Masked finite action-index set",
        tex: "\\mathcal{Q}_t=\\{q_{t,i}\\}_{i=1}^{N_t},\\quad \\mathcal{A}(s_t)=\\{i\\in\\{1,\\ldots,N_t\\}:m_{t,i}=1\\},\\quad q_t=q_{t,a_t}",
      ),
      formulae: (),
    ),
  ),
  (
    key: "counterfactual-transition",
    short: "transition",
    long: "Counterfactual Transition",
    description: "Deterministic or replayable rollout update that renders or retrieves only the selected candidate observation, backprojects it to candidate geometry, and fuses it into the accumulated reconstruction proxy.",
    group: "Planning",
    custom: (
      anchor: "term-counterfactual-transition",
      aliases: (
        "rollout transition",
        "candidate fusion update",
        "counterfactual update",
      ),
      category: "planning.mdp",
      parent: "target-conditioned-nbv-mdp",
      definition_short: "Replayable state update after selecting a candidate index.",
      definition_long: "For the thesis-core ASE mesh/oracle loop, the transition uses the selected candidate index to render or retrieve that candidate's depth, backproject points, and update the counterfactual point state and selected-view history. All-candidate GT renders and scores remain oracle-only before selection. The update must be deterministic under the stored seed and lineage.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#rl-planning-theory",
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/reference/aria_nbv.rollouts.CounterfactualPoseGenerator.qmd",
      ),
      citations: (),
      related: (
        "rollout-state",
        "point-cloud",
        "oracle-rri",
      ),
      kg_tags: (
        "planning",
        "counterfactual",
        "transition",
      ),
      tier: "core",
      lookup_rank: 160,
      symbol_refs: (
        "rl.transition",
        "oracle.points",
        "oracle.points_q",
      ),
      equation_refs: (
        "rl.counterfactual_transition",
      ),
      typst_macro: none,
      notation: (
        typst: "$T(s_t,a_t)$",
      ),
      formula: (
        label: "Point-state transition",
        tex: "\\mathcal{P}_{t+1}=\\mathcal{P}_t\\cup\\mathcal{P}_{q_t}",
      ),
      formulae: (),
    ),
  ),
  (
    key: "target-rri-reward",
    short: "reward",
    long: "Target-RRI Reward",
    description: "Quality-only immediate reward for thesis-core target-aware rollouts. It is the target-specific point-mesh error reduction normalized by the rollout-root target error; scalar motion, rule, diversity, and validity penalties are later ablations.",
    group: "Metrics",
    custom: (
      anchor: "term-target-rri-reward",
      aliases: (
        "target reward",
        "quality reward",
        "target-specific RRI reward",
      ),
      category: "metrics.reconstruction_quality",
      parent: "target-specific-rri",
      definition_short: "Quality-only immediate reward equal to root-normalized target gain for the selected candidate.",
      definition_long: "The main thesis reward is cumulative root-normalized target gain under equal acquisition budget. State-relative target RRI remains a one-step diagnostic and VIN-compatible label; log-improvement variants remain visible follow-up reward ablations, not the default target for the first Q_H result.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq1-objective",
        "docs/contents/theory/rl_planning.qmd#rl-planning-theory",
        "docs/contents/thesis/roadmap.qmd#roadmap-m5",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "target-specific-rri",
        "finite-horizon-return",
        "acquisition-cost",
      ),
      kg_tags: (
        "metric",
        "reward",
        "thesis-core",
      ),
      tier: "core",
      lookup_rank: 170,
      symbol_refs: (
        "rl.reward_target",
        "entity.rri_e",
        "oracle.points",
        "ase.mesh_target",
      ),
      equation_refs: (
        "rl.target_rri_reward",
      ),
      typst_macro: none,
      notation: (
        typst: "$r_t^e$",
      ),
      formula: (
        label: "Target-RRI reward",
        tex: "r_t^e=\\mathrm{RRI}_e(q_t\\mid \\mathcal{P}_t,\\mathcal{M}_e^{\\mathrm{GT}})",
      ),
      formulae: (
        (
          label: "Log-improvement follow-up",
          tex: "r_t^{\\log,e}=\\log(D(\\mathcal{P}_t^e,\\mathcal{M}_e^{\\mathrm{GT}})+\\varepsilon)-\\log(D(\\mathcal{P}_{t+1}^e,\\mathcal{M}_e^{\\mathrm{GT}})+\\varepsilon)",
        ),
      ),
    ),
  ),
  (
    key: "finite-horizon-return",
    short: "return",
    long: "Finite-Horizon Return",
    description: [
      Symbolic H-step return used by ARIA-NBV rollout evaluation and #symb.rl.qh targets. The formula keeps $gamma$ explicit while the thesis-core comparison reports cumulative root-normalized target gain under equal acquisition budget.
    ],
    group: "Planning",
    custom: (
      anchor: "term-finite-horizon-return",
      aliases: (
        "H-step return",
        "bounded return",
        "cumulative target root gain",
      ),
      category: "planning.objective",
      parent: "target-conditioned-nbv-mdp",
      definition_short: "H-step discounted return over root-normalized target-gain rewards.",
      definition_long: "The return definition keeps gamma symbolic so discounted ablations remain possible. The first thesis result should report cumulative root-normalized target gain under an equal acquisition budget and treat log-improvement or scalarized rewards as follow-up analysis.",
      internal_links: (
        "docs/contents/theory/rl_planning.qmd#rl-planning-theory",
        "docs/contents/thesis/questions.qmd#rq4-planning",
      ),
      citations: (),
      related: (
        "target-rri-reward",
        "finite-horizon-q-function",
      ),
      kg_tags: (
        "planning",
        "return",
        "q-learning",
      ),
      tier: "core",
      lookup_rank: 180,
      symbol_refs: (
        "rl.return_h",
        "rl.reward_target",
        "rl.gamma",
        "rl.H",
      ),
      equation_refs: (
        "rl.finite_horizon_return",
      ),
      typst_macro: none,
      notation: (
        typst: "$G_t^((H))$",
      ),
      formula: (
        label: "Finite-horizon return",
        tex: "G_t^{(H)}=\\sum_{k=0}^{H-1}\\gamma^k r_{t+k}^e",
      ),
      formulae: (),
    ),
  ),
  (
    key: "finite-horizon-q-function",
    short: "Q_H",
    long: "Finite-Horizon Q Function",
    description: "Target-conditioned finite-candidate value function trained from ASE oracle rollout traces. The first thesis implementation uses candidate-to-state query attention and emits one masked continuous-return value per valid candidate-table action, using DQN-style replayed Bellman targets, Double-DQN selector/evaluator backups, and offline support constraints.",
    group: "Model",
    custom: (
      anchor: "term-finite-horizon-q-function",
      aliases: (
        "Q_H",
        "candidate-query Q_H",
        "bounded Q function",
        "finite-candidate Q",
        "fitted Double-Q head",
      ),
      category: "model.value",
      parent: "target-conditioned-nbv-mdp",
      definition_short: "Finite-horizon candidate-value function for target-conditioned ARIA-NBV.",
      definition_long: "The mandatory M5 learned policy-like result is Q_H over finite candidate sets. The first-path architecture uses candidate-to-state query attention: encode s_t^{cf0}, actor-visible target descriptor phi_e, selected-view history, budget state, scene-memory summaries, and candidate tokens, then emit one continuous return value per candidate. DQN contributes replayed transition learning and Bellman-style finite-action value targets; Double DQN contributes the masked online-selector / target-evaluator backup to reduce max-over-candidate overestimation; IQL contributes the offline support rule that value learning must not query invalid, ungenerated, or unavailable actions. Q_H must respect validity masks and beat one-step greedy or model scoring on cumulative root-normalized target gain under equal acquisition budget, with bounded oracle lookahead as an upper bound.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq4-planning",
        "docs/contents/thesis/roadmap.qmd#roadmap-m5",
        "docs/contents/theory/rl_planning.qmd#q-h-training-contract",
        "docs/contents/literature/rl_planning.qmd#q-h-and-dqn",
      ),
      citations: (
        "DBLP:journals/corr/MnihKSGAWR13",
        "DoubleDQN-vanHasselt2015",
        "IQL-kostrikov2021",
      ),
      related: (
        "finite-horizon-return",
        "minimal-counterfactual-state",
        "predicted-target-q",
        "validity-mask",
      ),
      kg_tags: (
        "model",
        "q-learning",
        "thesis-core",
      ),
      tier: "core",
      lookup_rank: 190,
      symbol_refs: (
        "rl.qh",
        "rl.return_h",
        "rl.s_cf0",
        "rl.a",
      ),
      equation_refs: (
        "rl.q_h",
        "rl.q_backup",
      ),
      typst_macro: none,
      notation: (
        typst: "$Q_H$",
      ),
      formula: (
        label: "Finite-horizon candidate value",
        tex: "Q_H(s_t^{\\mathrm{cf0}},a_t,\\boldsymbol{\\phi}_e)=\\mathbb{E}\\left[G_t^{(H)}\\mid s_t=s_t^{\\mathrm{cf0}},a_t,\\boldsymbol{\\phi}_e\\right]",
      ),
      formulae: (
        (
          label: "Masked Double-DQN selector",
          tex: "j^*=\\arg\\max_{j:m_{t+1,j}=1}Q_\\theta(s_{t+1}^{\\mathrm{cf0}},a_{t+1,j},\\boldsymbol{\\phi}_e)",
        ),
        (
          label: "Masked Double-DQN target",
          tex: "y_t=r_t^e+\\gamma(1-d_t)Q_{\\bar\\theta}(s_{t+1}^{\\mathrm{cf0}},a_{t+1,j^*},\\boldsymbol{\\phi}_e)",
        ),
      ),
    ),
  ),
  (
    key: "validity-mask",
    short: "mask",
    long: "Validity Mask",
    description: [
      Hard candidate-level feasibility mask used during candidate ranking, rollout generation, and #symb.rl.qh training. Invalidity is represented separately from reconstruction quality and should not be encoded as the lowest RRI class.
    ],
    group: "Planning",
    custom: (
      anchor: "term-validity-mask",
      aliases: (
        "candidate validity mask",
        "action mask",
        "invalid action mask",
      ),
      category: "planning.constraints",
      parent: "finite-candidate-action-set",
      definition_short: "Hard mask that separates feasible candidate actions from invalid candidates.",
      definition_long: "The mask m_{t,i} gates candidate actions, while invalid reason codes rho_{t,i} preserve why a candidate was rejected. Collision, outside-bounds poses, no target visibility, bad frusta, no depth hits, and outside-EVL-extent cases are constraints rather than low target-RRI examples.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq-evidence-protocol",
        "docs/reference/aria_nbv.pose_generation.CandidateSamplingResult.qmd",
      ),
      citations: (),
      related: (
        "finite-candidate-action-set",
        "finite-horizon-q-function",
        "target-rri-reward",
      ),
      kg_tags: (
        "planning",
        "validity",
        "constraint",
      ),
      tier: "core",
      lookup_rank: 200,
      symbol_refs: (
        "rl.validity_mask",
        "rl.invalid_reason",
        "vin.cand_valid",
      ),
      equation_refs: (
        "metrics.candidate_validity",
        "rl.finite_action_set",
      ),
      typst_macro: none,
      notation: (
        typst: "$m_(t,i)$",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "project-aria",
    short: "Project Aria",
    long: "Project Aria",
    description: "Meta's egocentric research-device and tooling ecosystem for calibrated, time-aligned multimodal sensing. ARIA-NBV treats Project Aria and its MPS-style products as the actor-visible sensing contract, while ASE meshes remain offline supervision and evaluation assets.",
    group: "Dataset",
    custom: (
      anchor: "term-project-aria",
      aliases: (
        "Aria",
        "Project Aria ecosystem",
      ),
      category: "dataset.project_aria",
      parent: "dataset",
      definition_short: "Egocentric research-device and tooling ecosystem for calibrated, time-aligned multimodal sensing.",
      definition_long: "ARIA-NBV treats Project Aria and its MPS-style products as the actor-visible sensing contract, while ASE meshes remain offline supervision and evaluation assets.",
      internal_links: (
        "docs/contents/literature/project_aria.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "projectaria-engel2023",
      ),
      related: (
        "machine-perception-services",
        "aria-synthetic-environments",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "dataset",
        "egocentric",
        "project-aria",
      ),
      tier: "core",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "aria-synthetic-environments",
    short: "ASE",
    long: "Aria Synthetic Environments",
    description: "Large-scale synthetic indoor dataset with simulated Project Aria sensor characteristics, egocentric trajectories, and scene annotations. ARIA-NBV uses ASE snippets and the public mesh-supervised subset to generate oracle RRI labels from ground-truth meshes and semi-dense point clouds.",
    group: "Dataset",
    custom: (
      anchor: "term-aria-synthetic-environments",
      aliases: (
        "Aria Synthetic Environment",
        "ASE dataset",
      ),
      category: "dataset.synthetic",
      parent: "dataset",
      definition_short: "Large-scale synthetic indoor dataset with simulated Project Aria sensor characteristics, egocentric trajectories, and scene annotations.",
      definition_long: "ARIA-NBV uses ASE snippets and the public mesh-supervised subset to generate oracle RRI labels from ground-truth meshes and semi-dense point clouds.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/setup.qmd#aria-synthetic-environments",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "snippet",
        "egocentric-foundation-model-3d",
        "oracle-rri",
      ),
      kg_tags: (
        "dataset",
        "synthetic",
        "project-aria",
      ),
      typst_macro: "ASE",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "egocentric-foundation-model-3d",
    short: "EFM3D",
    long: "Egocentric Foundation Model 3D",
    description: "Egocentric 3D foundation-model stack used as the frozen spatial backbone for ARIA-NBV candidate scoring. The current project uses EFM3D and its EVL architecture to expose voxel occupancy, centerness, semantic, and OBB evidence for VIN-style RRI prediction.",
    group: "Model",
    custom: (
      anchor: "term-egocentric-foundation-model-3d",
      aliases: (
        "EFM",
        "egocentric foundation model",
      ),
      category: "model.backbone",
      parent: "foundation-model",
      definition_short: "Egocentric 3D foundation-model stack used as the frozen spatial backbone for ARIA-NBV candidate scoring.",
      definition_long: "The current project uses EFM3D and its EVL architecture to expose voxel occupancy, centerness, semantic, and OBB evidence for VIN-style RRI prediction.",
      internal_links: (
        "docs/contents/literature/efm3d.qmd",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
        "docs/reference/aria_nbv.vin.backbones.evl.EvlBackbone.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "egocentric-voxel-lifting",
        "view-introspection-network",
        "aria-synthetic-environments",
      ),
      kg_tags: (
        "foundation-model",
        "backbone",
        "evl",
      ),
      typst_macro: "EFM3D",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "egocentric-voxel-lifting",
    short: "EVL",
    long: "Egocentric Voxel Lifting",
    description: "EFM3D architecture that lifts synchronized egocentric observations into a gravity-aligned 3D voxel feature volume. ARIA-NBV uses EVL head outputs, pre-head features, and OBB predictions as local actor-visible evidence and target support, not as the complete frozen scene representation.",
    group: "Model",
    custom: (
      anchor: "term-egocentric-voxel-lifting",
      aliases: (
        "voxel lifting",
        "EVL backbone",
      ),
      category: "model.backbone",
      parent: "egocentric-foundation-model-3d",
      definition_short: "EFM3D architecture that lifts synchronized egocentric observations into a gravity-aligned 3D voxel feature volume.",
      definition_long: "ARIA-NBV uses EVL head outputs, pre-head features, and OBB predictions as local actor-visible evidence and target support for VIN-style RRI prediction. Broader NBV scene embeddings may combine semidense or fused point state with lifted image-foundation features.",
      internal_links: (
        "docs/contents/literature/efm3d.qmd",
        "docs/contents/theory/efm3d_scene_embeddings.qmd",
        "docs/reference/aria_nbv.vin.backbones.evl.EvlBackbone.qmd",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
        "EVL-Doc-2025",
      ),
      related: (
        "egocentric-foundation-model-3d",
        "view-introspection-network",
        "oriented-bounding-box",
      ),
      kg_tags: (
        "backbone",
        "voxel",
        "evl",
      ),
      typst_macro: "EVL",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "oriented-bounding-box",
    short: "OBB",
    long: "Oriented Bounding Box",
    description: "3D bounding box with arbitrary orientation, used to represent object extent more tightly than an axis-aligned box. OBBs are a natural target encoding for entity-aware ARIA-NBV because they provide center, extent, orientation, semantic class, and confidence signals.",
    group: "Geometry",
    custom: (
      anchor: "term-oriented-bounding-box",
      aliases: (
        "oriented box",
        "object box",
      ),
      category: "geometry.annotation",
      parent: "object-geometry",
      definition_short: "3D bounding box with arbitrary orientation, used to represent object extent more tightly than an axis-aligned box.",
      definition_long: "OBBs are a natural target encoding for entity-aware ARIA-NBV because they provide center, extent, orientation, semantic class, and confidence signals.",
      internal_links: (
        "docs/contents/ase_dataset.qmd#oriented-bounding-boxes",
        "docs/contents/thesis/questions.qmd#rq2-target-encoding",
        "docs/reference/vin.types.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "target-of-interest",
        "target-conditioned-scorer",
        "egocentric-voxel-lifting",
      ),
      kg_tags: (
        "geometry",
        "entity-aware",
        "annotation",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "frustum",
    short: "frustum",
    long: "Frustum",
    description: "Truncated pyramidal camera-visible volume bounded by near and far clipping planes plus lateral field-of-view planes. Candidate-view frusta define which scene surfaces can project into a camera image and are therefore central to visibility, rendering, and RRI diagnostics.",
    group: "Geometry",
    custom: (
      anchor: "term-frustum",
      aliases: (
        "viewing frustum",
        "camera frustum",
      ),
      category: "geometry.camera",
      parent: "camera-geometry",
      definition_short: "Truncated pyramidal camera-visible volume bounded by near and far clipping planes plus lateral field-of-view planes.",
      definition_long: "Candidate-view frusta define which scene surfaces can project into a camera image and are therefore central to visibility, rendering, and RRI diagnostics.",
      internal_links: (
        "docs/contents/theory/rri_theory.qmd",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
      ),
      citations: (
        "Frustum-Wikipedia-2025",
      ),
      related: (
        "candidate-view",
        "egocentric-voxel-lifting",
        "point-cloud",
      ),
      kg_tags: (
        "geometry",
        "camera",
        "visibility",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "left-up-forward",
    short: "LUF",
    long: "Left-Up-Forward",
    description: "Camera coordinate convention whose x axis points left, y axis points up, and z axis points forward. LUF is one of the coordinate-frame conventions that must stay explicit when moving between Project Aria cameras, PyTorch3D cameras, and ARIA-NBV candidate poses.",
    group: "Geometry",
    custom: (
      anchor: "term-left-up-forward",
      aliases: (
        "LUF frame",
        "left up forward",
      ),
      category: "geometry.frames",
      parent: "coordinate-frame",
      definition_short: "Camera coordinate convention whose x axis points left, y axis points up, and z axis points forward.",
      definition_long: "LUF is one of the coordinate-frame conventions that must stay explicit when moving between Project Aria cameras, PyTorch3D cameras, and ARIA-NBV candidate poses.",
      internal_links: (
        "docs/typst/seminar_paper/sections/05-coordinate-conventions.typ",
        "docs/typst/seminar_paper/sections/12f-appendix-pose-frames.typ",
      ),
      citations: (),
      related: (
        "candidate-view",
        "frustum",
      ),
      kg_tags: (
        "geometry",
        "coordinate-frame",
        "camera",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "simultaneous-localization-and-mapping",
    short: "SLAM",
    long: "Simultaneous Localization and Mapping",
    description: "Method for estimating sensor motion while building a map of the surrounding scene. In ARIA-NBV, logged SLAM poses and semi-dense points form the current reconstruction state against which candidate-view RRI is evaluated.",
    group: "Reconstruction",
    custom: (
      anchor: "term-simultaneous-localization-and-mapping",
      aliases: (
        "visual SLAM",
        "mapping and localization",
      ),
      category: "reconstruction.state",
      parent: "reconstruction",
      definition_short: "Method for estimating sensor motion while building a map of the surrounding scene.",
      definition_long: "In ARIA-NBV, logged SLAM poses and semi-dense points form the current reconstruction state against which candidate-view RRI is evaluated.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "point-cloud",
        "snippet",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "reconstruction",
        "pose",
        "project-aria",
      ),
      typst_macro: "SLAM",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "visual-inertial-odometry",
    short: "VIO",
    long: "Visual-Inertial Odometry",
    description: "Pose-estimation method that combines visual measurements from cameras with inertial measurements from IMUs. Project Aria pose and mapping products build on visual-inertial estimation, and ARIA-NBV depends on those pose streams for snippet state and candidate frame contracts.",
    group: "Reconstruction",
    custom: (
      anchor: "term-visual-inertial-odometry",
      aliases: (
        "visual inertial odometry",
        "inertial visual odometry",
      ),
      category: "reconstruction.pose",
      parent: "simultaneous-localization-and-mapping",
      definition_short: "Pose-estimation method that combines visual measurements from cameras with inertial measurements from IMUs.",
      definition_long: "Project Aria pose and mapping products build on visual-inertial estimation, and ARIA-NBV depends on those pose streams for snippet state and candidate frame contracts.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/theory/semi-dense-pc.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "simultaneous-localization-and-mapping",
        "motion-trajectory-data",
      ),
      kg_tags: (
        "pose",
        "reconstruction",
        "project-aria",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "point-cloud",
    short: "PC",
    long: "Point Cloud",
    description: "Set of 3D points representing observed scene geometry. ARIA-NBV compares current and candidate-fused point clouds against ground-truth meshes to compute oracle RRI and surface-distance diagnostics.",
    group: "Reconstruction",
    custom: (
      anchor: "term-point-cloud",
      aliases: (
        "3D points",
        "semi-dense point cloud",
      ),
      category: "reconstruction.representation",
      parent: "reconstruction",
      definition_short: "Set of 3D points representing observed scene geometry.",
      definition_long: "ARIA-NBV compares current and candidate-fused point clouds against ground-truth meshes to compute oracle RRI and surface-distance diagnostics.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
        "docs/contents/theory/surface_metrics.qmd",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (),
      related: (
        "relative-reconstruction-improvement",
        "oracle-rri",
        "simultaneous-localization-and-mapping",
      ),
      kg_tags: (
        "geometry",
        "reconstruction",
        "point-cloud",
      ),
      tier: "core",
      lookup_rank: 60,
      symbol_refs: (
        "oracle.points",
        "oracle.points_q",
      ),
      typst_macro: "PC",
      notation: (
        typst: "#symb.oracle.points",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "track",
    short: "track",
    long: "Track",
    description: "Temporal sequence of corresponding image-feature detections across frames, usually carrying per-frame image coordinates, timestamps, and camera IDs. Tracks can be triangulated or optimized into 3D points, making them a bridge between image evidence and the semi-dense point clouds used by ARIA-NBV.",
    group: "Reconstruction",
    custom: (
      anchor: "term-track",
      aliases: (
        "feature track",
        "2D track",
        "SLAM track",
      ),
      category: "reconstruction.features",
      parent: "simultaneous-localization-and-mapping",
      definition_short: "Temporal sequence of corresponding image-feature detections across frames, usually carrying per-frame image coordinates, timestamps, and camera IDs.",
      definition_long: "Tracks can be triangulated or optimized into 3D points, making them a bridge between image evidence and the semi-dense point clouds used by ARIA-NBV.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
      ),
      citations: (),
      related: (
        "point-cloud",
        "simultaneous-localization-and-mapping",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "feature-track",
        "slam",
        "reconstruction",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (
        tex: "\\mathcal{T}=\\{(u_k,v_k,\\mathrm{cam}_k,t_k)\\}_{k=0}^{N}",
      ),
      formulae: (),
    ),
  ),
  (
    key: "snippet",
    short: "snippet",
    long: "Snippet",
    description: "Short synchronized temporal window of Aria sensor data used as one EVL/VIN input sample. A snippet typically contains RGB or grayscale streams, poses, calibration, semi-dense points, and scene metadata that EVL lifts into a voxel grid.",
    group: "Dataset",
    custom: (
      anchor: "term-snippet",
      aliases: (
        "temporal window",
        "ASE snippet",
      ),
      category: "dataset.sample",
      parent: "aria-synthetic-environments",
      definition_short: "Short synchronized temporal window of Aria sensor data used as one EVL/VIN input sample.",
      definition_long: "A snippet typically contains RGB or grayscale streams, poses, calibration, semi-dense points, and scene metadata that EVL lifts into a voxel grid.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/reference/data_handling.ase_efm.dataset.qmd",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "aria-synthetic-environments",
        "egocentric-voxel-lifting",
        "view-introspection-network",
      ),
      kg_tags: (
        "dataset",
        "sample",
        "evl",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "central-pupil-frame",
    short: "CPF",
    long: "Central Pupil Frame",
    description: "Coordinate frame placed at the midpoint between the left and right eye boxes of Project Aria glasses. CPF is used by Project Aria for gaze-related quantities and should remain distinct from rig, camera, world, and PyTorch3D frames in ARIA-NBV docs.",
    group: "Dataset",
    custom: (
      anchor: "term-central-pupil-frame",
      aliases: (
        "central pupil coordinate frame",
      ),
      category: "dataset.frames",
      parent: "project-aria",
      definition_short: "Coordinate frame placed at the midpoint between the left and right eye boxes of Project Aria glasses.",
      definition_long: "CPF is used by Project Aria for gaze-related quantities and should remain distinct from rig, camera, world, and PyTorch3D frames in ARIA-NBV docs.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "left-up-forward",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "project-aria",
        "coordinate-frame",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "machine-perception-services",
    short: "MPS",
    long: "Machine Perception Services",
    description: "Project Aria processing services that derive pose, mapping, gaze, hand, and related perception outputs from sensor recordings. ARIA-NBV mainly depends on MPS-style pose and semi-dense mapping products as the current reconstruction state for RRI computation.",
    group: "Dataset",
    custom: (
      anchor: "term-machine-perception-services",
      aliases: (
        "Project Aria MPS",
      ),
      category: "dataset.project_aria",
      parent: "project-aria",
      definition_short: "Project Aria processing services that derive pose, mapping, gaze, hand, and related perception outputs from sensor recordings.",
      definition_long: "ARIA-NBV mainly depends on MPS-style pose and semi-dense mapping products as the current reconstruction state for RRI computation.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/theory/semi-dense-pc.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "simultaneous-localization-and-mapping",
        "point-cloud",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "project-aria",
        "data-product",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "motion-trajectory-data",
    short: "MTD",
    long: "Motion Trajectory Data",
    description: "Device poses over time, usually represented as a sequence of 6-DoF transformations. MTD supplies the logged egocentric trajectory used to define snippet state, current reconstruction context, and candidate-view reference poses.",
    group: "Dataset",
    custom: (
      anchor: "term-motion-trajectory-data",
      aliases: (
        "trajectory data",
        "pose stream",
      ),
      category: "dataset.stream",
      parent: "snippet",
      definition_short: "Device poses over time, usually represented as a sequence of 6-DoF transformations.",
      definition_long: "MTD supplies the logged egocentric trajectory used to define snippet state, current reconstruction context, and candidate-view reference poses.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/reference/data_handling.ase_efm.views.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "snippet",
        "visual-inertial-odometry",
        "candidate-view",
      ),
      kg_tags: (
        "dataset",
        "pose",
        "trajectory",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "multi-frame-camera-data",
    short: "MFCD",
    long: "Multi-Frame Camera Data",
    description: "Synchronized camera streams from multiple Project Aria cameras over a temporal window. MFCD provides the egocentric image evidence consumed by EVL and aligned with pose, calibration, and semi-dense point streams.",
    group: "Dataset",
    custom: (
      anchor: "term-multi-frame-camera-data",
      aliases: (
        "multi-camera frame data",
        "synchronized camera data",
      ),
      category: "dataset.stream",
      parent: "snippet",
      definition_short: "Synchronized camera streams from multiple Project Aria cameras over a temporal window.",
      definition_long: "MFCD provides the egocentric image evidence consumed by EVL and aligned with pose, calibration, and semi-dense point streams.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
        "docs/contents/literature/efm3d.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
        "EFM3D-straub2024",
      ),
      related: (
        "snippet",
        "egocentric-voxel-lifting",
        "visual-inertial-odometry",
      ),
      kg_tags: (
        "dataset",
        "camera",
        "evl",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "multi-semi-dense-point-data",
    short: "MSDPD",
    long: "Multi-Semi-Dense Point Data",
    description: "Semi-dense 3D point observations generated by SLAM-style processing across a snippet or trajectory window. MSDPD is the sparse observed geometry that ARIA-NBV fuses with candidate point clouds and compares against ground-truth meshes for RRI labels.",
    group: "Dataset",
    custom: (
      anchor: "term-multi-semi-dense-point-data",
      aliases: (
        "multi-frame semi-dense points",
        "semi-dense point stream",
      ),
      category: "dataset.stream",
      parent: "snippet",
      definition_short: "Semi-dense 3D point observations generated by SLAM-style processing across a snippet or trajectory window.",
      definition_long: "MSDPD is the sparse observed geometry that ARIA-NBV fuses with candidate point clouds and compares against ground-truth meshes for RRI labels.",
      internal_links: (
        "docs/contents/theory/semi-dense-pc.qmd",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "point-cloud",
        "simultaneous-localization-and-mapping",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "dataset",
        "point-cloud",
        "reconstruction",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "virtual-reality-standard",
    short: "VRS",
    long: "Virtual Reality Standard",
    description: "File format used by Project Aria tooling to store multi-modal sensor recordings efficiently. VRS is part of the upstream Project Aria ecosystem, while ARIA-NBV primarily consumes ASE/ATEK-derived tensorized snippets for current experiments.",
    group: "Dataset",
    custom: (
      anchor: "term-virtual-reality-standard",
      aliases: (
        "VRS file",
        "Project Aria VRS",
      ),
      category: "dataset.file_format",
      parent: "project-aria",
      definition_short: "File format used by Project Aria tooling to store multi-modal sensor recordings efficiently.",
      definition_long: "VRS is part of the upstream Project Aria ecosystem, while ARIA-NBV primarily consumes ASE/ATEK-derived tensorized snippets for current experiments.",
      internal_links: (
        "docs/contents/setup.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "ProjectAria-ASE-2025",
      ),
      related: (
        "snippet",
        "multi-frame-camera-data",
        "motion-trajectory-data",
      ),
      kg_tags: (
        "project-aria",
        "file-format",
        "dataset",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "scene-script-language",
    short: "SSL",
    long: "SceneScript Language",
    description: "Structured language representation for indoor scene layout using primitives such as walls, doors, windows, and objects. SceneScript is relevant to ARIA-NBV as a possible semantic/global planning layer and as one source of ASE scene-structure context.",
    group: "Dataset",
    custom: (
      anchor: "term-scene-script-language",
      aliases: (
        "Structure Scene Language",
        "SceneScript structured language",
      ),
      category: "dataset.scene_representation",
      parent: "scene-representation",
      definition_short: "Structured language representation for indoor scene layout using primitives such as walls, doors, windows, and objects.",
      definition_long: "SceneScript is relevant to ARIA-NBV as a possible semantic/global planning layer and as one source of ASE scene-structure context.",
      internal_links: (
        "docs/contents/literature/scene_script.qmd",
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "SceneScript-avetisyan2024",
      ),
      related: (
        "aria-synthetic-environments",
        "target-of-interest",
        "next-best-view",
      ),
      kg_tags: (
        "scene-representation",
        "semantics",
        "extension",
      ),
      tier: "background",
      typst_macro: "SSL",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "candidate-view",
    short: "candidate",
    long: "Candidate View",
    description: "Proposed camera pose whose expected reconstruction utility is evaluated before selecting the next observation. ARIA-NBV samples candidate views around a reference pose or target, renders candidate depths from the mesh for oracle labels, and scores candidates with RRI or learned VIN predictions.",
    group: "Planning",
    custom: (
      anchor: "term-candidate-view",
      aliases: (
        "candidate pose",
        "candidate viewpoint",
        "next-view candidate",
      ),
      category: "planning.action",
      parent: "next-best-view",
      definition_short: "Proposed camera pose whose expected reconstruction utility is evaluated before selecting the next observation.",
      definition_long: "ARIA-NBV samples candidate views around a reference pose or target, renders candidate depths from the mesh for oracle labels, and scores candidates with RRI or learned VIN predictions.",
      internal_links: (
        "docs/contents/thesis/questions.qmd#rq3-candidates",
        "docs/contents/theory/rri_theory.qmd",
        "docs/reference/aria_nbv.pose_generation.CandidateViewGenerator.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "next-best-view",
        "oracle-rri",
        "target-conditioned-scorer",
      ),
      kg_tags: (
        "planning",
        "action-space",
        "candidate-generation",
      ),
      tier: "core",
      lookup_rank: 70,
      symbol_refs: (
        "oracle.candidates_t",
        "oracle.candidate_qti",
      ),
      typst_macro: none,
      notation: (
        typst: "#symb.oracle.candidates",
      ),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "oracle-rri",
    short: "oracle RRI",
    long: "Oracle RRI",
    description: "RRI label computed with privileged ground-truth geometry, used for supervised training and evaluation. The current oracle renders candidate depth maps from ASE ground-truth meshes, backprojects candidate point clouds, fuses them with the current semi-dense reconstruction, and scores the resulting surface-distance improvement.",
    group: "Supervision",
    custom: (
      anchor: "term-oracle-rri",
      aliases: (
        "RRI oracle",
        "oracle label",
        "mesh-supervised RRI",
      ),
      category: "supervision.oracle",
      parent: "relative-reconstruction-improvement",
      definition_short: "RRI label computed with privileged ground-truth geometry, used for supervised training and evaluation.",
      definition_long: "The current oracle renders candidate depth maps from ASE ground-truth meshes, backprojects candidate point clouds, fuses them with the current semi-dense reconstruction, and scores the resulting surface-distance improvement.",
      internal_links: (
        "docs/contents/theory/rri_theory.qmd",
        "docs/contents/ase_dataset.qmd",
        "docs/contents/thesis/roadmap.qmd#roadmap-m1",
      ),
      citations: (
        "VIN-NBV-frahm2025",
        "EFM3D-straub2024",
      ),
      related: (
        "relative-reconstruction-improvement",
        "candidate-view",
        "aria-synthetic-environments",
      ),
      kg_tags: (
        "oracle",
        "supervision",
        "mesh",
      ),
      tier: "core",
      lookup_rank: 80,
      symbol_refs: (
        "oracle.rri",
        "ase.mesh",
      ),
      equation_refs: (
        "rri.rri",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "view-introspection-network",
    short: "VIN",
    long: "View Introspection Network",
    description: "Learned candidate-view scorer that predicts RRI or an ordinal RRI-derived utility without capturing the candidate view. ARIA-NBV adapts VIN-NBV by placing a lightweight RRI prediction head on top of frozen EVL features and candidate-pose evidence from ASE snippets.",
    group: "Model",
    custom: (
      anchor: "term-view-introspection-network",
      aliases: (
        "VIN scorer",
        "VIN-NBV model",
        "Aria-VIN-NBV",
      ),
      category: "model.scoring",
      parent: "next-best-view",
      definition_short: "Learned candidate-view scorer that predicts RRI or an ordinal RRI-derived utility without capturing the candidate view.",
      definition_long: "ARIA-NBV adapts VIN-NBV by placing a lightweight RRI prediction head on top of frozen EVL features and candidate-pose evidence from ASE snippets.",
      internal_links: (
        "docs/contents/literature/vin_nbv.qmd",
        "docs/reference/vin.models.scene_myopic.qmd",
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "target-conditioned-scorer",
        "egocentric-voxel-lifting",
      ),
      kg_tags: (
        "model",
        "vin",
        "candidate-scoring",
      ),
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "coverage-ratio",
    short: "CR",
    long: "Coverage Ratio",
    description: "Fraction of a target surface, scene, or region treated as observed under a chosen visibility or distance threshold. Coverage ratio is a useful diagnostic baseline for NBV, but ARIA-NBV treats reconstruction-quality improvement through RRI as the preferred optimization target.",
    group: "Metrics",
    custom: (
      anchor: "term-coverage-ratio",
      aliases: (
        "coverage ratio",
      ),
      category: "metrics.coverage",
      parent: "evaluation-metric",
      definition_short: "Fraction of a target surface, scene, or region treated as observed under a chosen visibility or distance threshold.",
      definition_long: "Coverage ratio is a useful diagnostic baseline for NBV, but ARIA-NBV treats reconstruction-quality improvement through RRI as the preferred optimization target.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "candidate-view",
      ),
      kg_tags: (
        "metric",
        "coverage",
      ),
      typst_macro: "CR",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "chamfer-distance",
    short: "CD",
    long: "Chamfer Distance",
    description: [
      Historical bidirectional distance family used to compare reconstructed points against reference geometry. Thesis-facing ARIA-NBV notation uses point-mesh error #symb.oracle.err with directional components #symb.oracle.acc and #symb.oracle.comp#text[;] older seminar material may still call this CD.
    ],
    group: "Metrics",
    custom: (
      anchor: "term-chamfer-distance",
      aliases: (
        "Chamfer metric",
      ),
      category: "metrics.reconstruction_quality",
      parent: "reconstruction-quality",
      definition_short: "Historical bidirectional distance family used to compare reconstructed points against reference geometry.",
      definition_long: "Thesis-facing ARIA-NBV notation uses point-mesh error D with directional components D_{P->M} and D_{M->P}; older seminar material may still call this CD.",
      internal_links: (
        "docs/reference/rri_metrics.point_mesh.qmd",
        "docs/contents/theory/rri_theory.qmd",
      ),
      citations: (
        "VIN-NBV-frahm2025",
      ),
      related: (
        "relative-reconstruction-improvement",
        "point-cloud",
        "ground-truth",
      ),
      kg_tags: (
        "metric",
        "reconstruction-quality",
      ),
      tier: "core",
      lookup_rank: 25,
      symbol_refs: (
        "rri.cd_value",
        "oracle.points",
        "ase.mesh",
      ),
      equation_refs: (
        "rri.cd",
      ),
      typst_macro: "CD",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "degrees-of-freedom",
    short: "DoF",
    long: "Degrees of Freedom",
    description: "Number of independent pose parameters available to a camera, object, or action representation. ARIA-NBV distinguishes full 6-DoF pose estimation from reduced 5-DoF candidate or action spaces used for practical view planning.",
    group: "Geometry",
    custom: (
      anchor: "term-degrees-of-freedom",
      aliases: (
        "DoF",
      ),
      category: "geometry.pose",
      parent: "pose",
      definition_short: "Number of independent pose parameters available to a camera, object, or action representation.",
      definition_long: "ARIA-NBV distinguishes full 6-DoF pose estimation from reduced 5-DoF candidate or action spaces used for practical view planning.",
      internal_links: (
        "docs/typst/seminar_paper/sections/05-coordinate-conventions.typ",
        "docs/typst/seminar_paper/sections/12f-appendix-pose-frames.typ",
      ),
      citations: (),
      related: (
        "candidate-view",
      ),
      kg_tags: (
        "geometry",
        "pose",
      ),
      tier: "background",
      typst_macro: "DoF",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "six-degrees-of-freedom",
    short: "6DoF",
    long: "Six Degrees of Freedom",
    description: "Pose parameterization with three translational and three rotational degrees of freedom. Project Aria poses, candidate cameras, and world-to-device transforms are usually represented as 6-DoF rigid-body transforms.",
    group: "Geometry",
    custom: (
      anchor: "term-six-degrees-of-freedom",
      aliases: (
        "6-DoF",
        "6 degrees of freedom",
      ),
      category: "geometry.pose",
      parent: "degrees-of-freedom",
      definition_short: "Pose parameterization with three translational and three rotational degrees of freedom.",
      definition_long: "Project Aria poses, candidate cameras, and world-to-device transforms are usually represented as 6-DoF rigid-body transforms.",
      internal_links: (
        "docs/typst/seminar_paper/sections/05-coordinate-conventions.typ",
        "docs/typst/seminar_paper/sections/12f-appendix-pose-frames.typ",
      ),
      citations: (),
      related: (
        "candidate-view",
        "degrees-of-freedom",
      ),
      kg_tags: (
        "geometry",
        "pose",
      ),
      tier: "background",
      typst_macro: "SixDoF",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "five-degrees-of-freedom",
    short: "5DoF",
    long: "Five Degrees of Freedom",
    description: "Reduced camera-action parameterization commonly used when roll is fixed or otherwise constrained. ARIA-NBV uses 5-DoF language for candidate and planning abstractions where position and viewing direction matter while roll is not an independently optimized control dimension.",
    group: "Planning",
    custom: (
      anchor: "term-five-degrees-of-freedom",
      aliases: (
        "5-DoF",
        "5 degrees of freedom",
      ),
      category: "planning.action_space",
      parent: "degrees-of-freedom",
      definition_short: "Reduced camera-action parameterization commonly used when roll is fixed or otherwise constrained.",
      definition_long: "ARIA-NBV uses 5-DoF language for candidate and planning abstractions where position and viewing direction matter while roll is not an independently optimized control dimension.",
      internal_links: (
        "docs/contents/thesis/roadmap.qmd",
        "docs/typst/seminar_paper/sections/10a-extensions.typ",
      ),
      citations: (
        "GenNBV-chen2024",
      ),
      related: (
        "candidate-view",
        "next-best-view",
        "degrees-of-freedom",
      ),
      kg_tags: (
        "planning",
        "action-space",
      ),
      tier: "background",
      typst_macro: "FiveDoF",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "area-under-curve",
    short: "AUC",
    long: "Area Under Curve",
    description: "Aggregate score computed by integrating a metric curve over an acquisition, threshold, or ranking axis. AUC can summarize how quickly reconstruction quality, coverage, or ranking quality improves as views are acquired or candidate thresholds change.",
    group: "Metrics",
    custom: (
      anchor: "term-area-under-curve",
      aliases: (
        "AUC",
      ),
      category: "metrics.evaluation",
      parent: "evaluation-metric",
      definition_short: "Aggregate score computed by integrating a metric curve over an acquisition, threshold, or ranking axis.",
      definition_long: "AUC can summarize how quickly reconstruction quality, coverage, or ranking quality improves as views are acquired or candidate thresholds change.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
      ),
      citations: (),
      related: (
        "acquisition-cost",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "metric",
        "evaluation",
      ),
      typst_macro: "AUC",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "multi-view-stereo",
    short: "MVS",
    long: "Multi-view Stereo",
    description: "Reconstruction family that estimates dense or semi-dense scene geometry from multiple calibrated views. MVS is part of the broader reconstruction context for NBV, although ARIA-NBV's current oracle labels are built from ASE meshes and Aria-style semi-dense point observations.",
    group: "Reconstruction",
    custom: (
      anchor: "term-multi-view-stereo",
      aliases: (
        "multi-view reconstruction",
      ),
      category: "reconstruction.geometry",
      parent: "reconstruction",
      definition_short: "Reconstruction family that estimates dense or semi-dense scene geometry from multiple calibrated views.",
      definition_long: "MVS is part of the broader reconstruction context for NBV, although ARIA-NBV's current oracle labels are built from ASE meshes and Aria-style semi-dense point observations.",
      internal_links: (
        "docs/contents/theory/nbv_background.qmd",
      ),
      citations: (),
      related: (
        "point-cloud",
        "next-best-view",
      ),
      kg_tags: (
        "reconstruction",
        "geometry",
      ),
      tier: "background",
      typst_macro: "MVS",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "three-dimensional-gaussian-splatting",
    short: "3DGS",
    long: "3D Gaussian Splatting",
    description: "Explicit radiance-field representation using optimized 3D Gaussian primitives for real-time novel-view synthesis. ARIA-NBV treats active 3DGS work as proposal, uncertainty, and simulator-bridge literature, not as a replacement for ASE mesh-supervised RRI.",
    group: "Representation",
    custom: (
      anchor: "term-three-dimensional-gaussian-splatting",
      aliases: (
        "3D Gaussian Splatting",
        "3DGS",
        "Gaussian splatting",
      ),
      category: "representation.radiance_field",
      parent: "radiance-field",
      definition_short: "Explicit radiance-field representation using optimized 3D Gaussian primitives for real-time novel-view synthesis.",
      definition_long: "ARIA-NBV treats active 3DGS work as proposal, uncertainty, and simulator-bridge literature, not as a replacement for ASE mesh-supervised RRI.",
      internal_links: (
        "docs/contents/literature/active_3dgs_nbv.qmd",
      ),
      citations: (
        "GaussianSplatting-kerbl2023",
      ),
      related: (
        "next-best-view",
        "relative-reconstruction-improvement",
      ),
      kg_tags: (
        "representation",
        "radiance-field",
        "3dgs",
      ),
      tier: "background",
      typst_macro: none,
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "occupancy-grid",
    short: "Occupancy Grid",
    long: "Occupancy Grid",
    description: "Spatial grid whose cells encode whether space is occupied, free, unknown, or represented by a related occupancy probability. Occupancy-style voxel evidence appears in EVL outputs and VIN feature construction, where it helps summarize local 3D scene state for candidate scoring.",
    group: "Representation",
    custom: (
      anchor: "term-occupancy-grid",
      aliases: (
        "occupancy volume",
      ),
      category: "representation.spatial",
      parent: "scene-representation",
      definition_short: "Spatial grid whose cells encode whether space is occupied, free, unknown, or represented by a related occupancy probability.",
      definition_long: "Occupancy-style voxel evidence appears in EVL outputs and VIN feature construction, where it helps summarize local 3D scene state for candidate scoring.",
      internal_links: (
        "docs/reference/aria_nbv.vin.models.scene_myopic.VinModelV3.qmd",
        "docs/typst/seminar_paper/sections/06-architecture.typ",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "egocentric-voxel-lifting",
        "view-introspection-network",
      ),
      kg_tags: (
        "representation",
        "voxel",
      ),
      typst_macro: "OccGrid",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "aria-digital-twin",
    short: "ADT",
    long: "Aria Digital Twin",
    description: "Project Aria dataset with real-world captures and digital-twin scene annotations. ADT is adjacent to ARIA-NBV's sim-to-real context; the current experiments focus on ASE and EFM3D/ATEK exports, while ADT remains a relevant transfer surface.",
    group: "Dataset",
    custom: (
      anchor: "term-aria-digital-twin",
      aliases: (
        "ADT",
      ),
      category: "dataset.aria",
      parent: "project-aria",
      definition_short: "Project Aria dataset with real-world captures and digital-twin scene annotations.",
      definition_long: "ADT is adjacent to ARIA-NBV's sim-to-real context; the current experiments focus on ASE and EFM3D/ATEK exports, while ADT remains a relevant transfer surface.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "aria-synthetic-environments",
        "aria-everyday-objects",
      ),
      kg_tags: (
        "dataset",
        "project-aria",
      ),
      tier: "background",
      typst_macro: "ADT",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
  (
    key: "aria-everyday-objects",
    short: "AEO",
    long: "Aria Everyday Objects",
    description: "Small-scale real-world Project Aria object dataset used by EFM3D for egocentric 3D perception evaluation. AEO is relevant as a possible sim-to-real check for ARIA-NBV ideas that are first developed on ASE mesh-supervised snippets.",
    group: "Dataset",
    custom: (
      anchor: "term-aria-everyday-objects",
      aliases: (
        "AEO",
      ),
      category: "dataset.aria",
      parent: "project-aria",
      definition_short: "Small-scale real-world Project Aria object dataset used by EFM3D for egocentric 3D perception evaluation.",
      definition_long: "AEO is relevant as a possible sim-to-real check for ARIA-NBV ideas that are first developed on ASE mesh-supervised snippets.",
      internal_links: (
        "docs/contents/ase_dataset.qmd",
      ),
      citations: (
        "EFM3D-straub2024",
      ),
      related: (
        "aria-synthetic-environments",
        "aria-digital-twin",
      ),
      kg_tags: (
        "dataset",
        "project-aria",
      ),
      tier: "background",
      typst_macro: "AEO",
      notation: (:),
      formula: (:),
      formulae: (),
    ),
  ),
)

#let aria-glossary-metadata(entry) = (
  id: entry.key,
  anchor: entry.custom.anchor,
  label: entry.long,
  short: entry.short,
  aliases: entry.custom.aliases,
  category: entry.custom.category,
  parent: entry.custom.parent,
  definition_short: entry.custom.definition_short,
  definition_long: entry.custom.definition_long,
  internal_links: entry.custom.internal_links,
  citations: entry.custom.citations,
  related: entry.custom.related,
  kg_tags: entry.custom.kg_tags,
  tier: entry.custom.at("tier", default: "support"),
  lookup_rank: entry.custom.at("lookup_rank", default: none),
  symbol_refs: entry.custom.at("symbol_refs", default: ()),
  equation_refs: entry.custom.at("equation_refs", default: ()),
  typst_macro: entry.custom.typst_macro,
  notation: entry.custom.notation,
  formula: entry.custom.formula,
  formulae: entry.custom.formulae,
)

#let register-aria-glossary() = register-glossary(aria-glossary-entries)
#let print-aria-glossary(..args) = print-glossary(aria-glossary-entries, ..args)
#let aria-glossary-reference-stub(label-key) = [
  #figure(kind: "glossarium_entry", supplement: "", numbering: none)[]#label(label-key)
]
#let aria-glossary-reference-stubs(entries, ..args) = {
  let labels = ()
  for entry in entries {
    let key = entry.key
    labels.push(key)
    labels.push(key + ":pl")
    labels.push(upper(key.first()) + key.slice(1))
    labels.push(upper(key.first()) + key.slice(1) + ":pl")
    if entry.short != none {
      labels.push(key + ":short")
    }
    if entry.long != none {
      labels.push(key + ":long")
    }
    if entry.at("description", default: none) != none {
      labels.push(key + ":description")
    }
    if entry.at("custom", default: none) != none {
      labels.push(key + ":custom")
    }
    if entry.at("longplural", default: none) != none {
      labels.push(key + ":longplural")
    }
  }
  for label-key in labels.dedup() {
    aria-glossary-reference-stub(label-key)
  }
}
#let load-aria-glossary-references(..args) = print-aria-glossary(
  show-all: true,
  disable-back-references: true,
  user-print-glossary: aria-glossary-reference-stubs,
  ..args,
)

#for entry in aria-glossary-entries [
  #metadata(aria-glossary-metadata(entry)) <aria-glossary-term>
]
