// Shared symbol dictionary composed from domain-specific modules.

#import "symbols/frame.typ": frame
#import "symbols/ase.typ": ase
#import "symbols/oracle.typ": oracle
#import "symbols/obs.typ": obs
#import "symbols/entity.typ": entity
#import "symbols/rl.typ": rl
#import "symbols/vin.typ": vin
#import "symbols/scene.typ": scene
#import "symbols/spatial.typ": spatial
#import "symbols/model.typ": model
#import "symbols/shape.typ": shape

#let symb = (
  frame: frame,
  ase: ase,
  oracle: oracle,
  obs: obs,
  entity: entity,
  rl: rl,
  vin: vin,
  scene: scene,
  spatial: spatial,
  model: model,
  shape: shape,
)

// Machine-readable notation records. `scripts/glossary_build.py` queries this
// canonical Typst source to derive every notation adapter.
#let aria-notation-symbols = (
  (key: "oracle.rri", tex: "\\mathrm{RRI}", description: "Relative Reconstruction Improvement score for a candidate view.", thesis_list: true, order: 10),
  (key: "oracle.points", tex: "\\mathcal{P}", description: "Actor-visible point set accumulated from observed or replayed views.", thesis_list: true, order: 20),
  (key: "oracle.points_q", tex: "\\mathcal{P}_q", description: "Candidate-view point contribution used in oracle or counterfactual updates.", thesis_list: true, order: 30),
  (key: "oracle.candidates", tex: "\\mathcal{Q}", description: "Finite candidate-view set considered by the planner.", thesis_list: true, order: 40),
  (key: "oracle.center", tex: "\\boldsymbol{c}", description: "World-space camera-center vector; subscripts identify a rollout root or candidate pose.", thesis_list: true, order: 65),
  (key: "oracle.depth_q", tex: "\\boldsymbol{D}_q", description: "Oracle-rendered or candidate-specific depth map for a proposed view.", thesis_list: true, order: 70),
  (key: "oracle.acc", tex: "D_{P\\to M}", description: "Point-to-mesh directional error component.", thesis_list: true, order: 80),
  (key: "oracle.comp", tex: "D_{M\\to P}", description: "Mesh-to-point directional error component.", thesis_list: true, order: 90),
  (key: "oracle.err", tex: "D", description: "Aggregate point-mesh reconstruction error used by RRI definitions.", thesis_list: true, order: 100),
  (key: "ase.mesh", tex: "\\mathcal{M}^{\\mathrm{GT}}", description: "Ground-truth scene mesh used for oracle labels and evaluation.", thesis_list: true, order: 110),
  (key: "ase.mesh_target", tex: "\\mathcal{M}_e^{\\mathrm{GT}}", description: "Ground-truth mesh crop for target e.", thesis_list: true, order: 120),
  (key: "ase.faces", tex: "\\mathcal{F}^{\\mathrm{GT}}", description: "Ground-truth mesh faces used in point-mesh distance calculations.", thesis_list: true, order: 130),
  (key: "ase.traj", tex: "\\boldsymbol{T}_{\\mathrm{rig}}^{\\mathrm{w}}(t)", description: "Project Aria rig pose in the world frame at time t.", thesis_list: true, order: 140),
  (key: "ase.traj_final", tex: "\\boldsymbol{T}_{\\mathrm{rig}}^{\\mathrm{w}}(T)", description: "Final rig pose used as an anchor for gravity-aligned local fields.", thesis_list: true, order: 150),
  (key: "vin.rri", tex: "r", description: "Historical VIN RRI proxy.", thesis_list: false, order: 160),
  (key: "vin.rri_hat", tex: "\\hat{r}", description: "Predicted RRI value emitted by the learned scorer.", thesis_list: true, order: 170),
  (key: "vin.loss", tex: "\\mathcal{L}", description: "Training loss for scorer or value-model objectives.", thesis_list: true, order: 180),
  (key: "vin.cand_valid", tex: "m", description: "Candidate validity indicator used by scorer diagnostics.", thesis_list: true, order: 190),
  (key: "entity.rri_e", tex: "\\mathrm{RRI}_e", description: "Target-specific Relative Reconstruction Improvement for entity e.", thesis_list: true, order: 200),
  (key: "entity.center", tex: "\\boldsymbol{p}_e^w", description: "World-space center of the selected target entity e.", thesis_list: true, order: 206),
  (key: "entity.target_rri_marginal", tex: "\\mathrm{RRI}_{t,i}^e", description: "State-relative marginal target RRI for candidate i at rollout step t.", thesis_list: true, order: 201),
  (key: "entity.target_rri_cumulative", tex: "C_t^{\\mathrm{RRI},e}", description: "Running sum of selected state-relative target RRIs.", thesis_list: true, order: 202),
  (key: "entity.target_root_gain_cumulative", tex: "J_t^e", description: "Running cumulative target gain normalized by rollout-root error.", thesis_list: true, order: 203),
  (key: "entity.target_error", tex: "\\Delta_t^e", description: "Target-specific reconstruction error at rollout step t.", thesis_list: true, order: 204),
  (key: "entity.target_desc", tex: "\\boldsymbol{\\phi}_e", description: "Actor-visible target/entity descriptor used to condition target-specific value prediction.", thesis_list: true, order: 205),
  (key: "rl.s", tex: "s", description: "Abstract planning state.", thesis_list: true, order: 210),
  (key: "rl.a", tex: "a", description: "Action index selecting a candidate row.", thesis_list: true, order: 220),
  (key: "rl.r", tex: "r", description: "Scalar reward or immediate gain.", thesis_list: true, order: 230),
  (key: "rl.G", tex: "G", description: "Finite-horizon return accumulated across rollout steps.", thesis_list: true, order: 240),
  (key: "rl.mdp_nbv", tex: "\\mathcal{M}_{\\mathrm{NBV}}", description: "Target-conditioned finite-candidate NBV decision process.", thesis_list: true, order: 250),
  (key: "rl.action_set", tex: "\\mathcal{A}(s_t)", description: "Valid action set available in state s_t.", thesis_list: true, order: 260),
  (key: "rl.transition", tex: "T", description: "State-transition operator for selected candidate actions.", thesis_list: true, order: 270),
  (key: "rl.s_hist", tex: "s_t^{\\mathrm{hist}}", description: "Logged historic snippet state at rollout step t.", thesis_list: true, order: 280),
  (key: "rl.s_off", tex: "s_t^{\\mathrm{off}}", description: "Persisted offline sample state used by training readers.", thesis_list: true, order: 290),
  (key: "rl.s_cf0", tex: "s_t^{\\mathrm{cf0}}", description: "Minimal actor-visible counterfactual state.", thesis_list: true, order: 300),
  (key: "rl.s_pose", tex: "s_t^{\\mathrm{S0-pose}}", description: "Implemented fixed-root pose-history state used by qh_cf0_v1.", thesis_list: true, order: 301),
  (key: "rl.s_cf_geom", tex: "s_t^{\\mathrm{cf+}}", description: "Geometry-enriched counterfactual successor state.", thesis_list: true, order: 310),
  (key: "rl.s_cf_gt_carrier", tex: "s_t^{\\mathrm{CF-GT-carrier}}", description: "Implemented privileged selected-depth carrier used by qh_cfplus_gt_depth_v1.", thesis_list: true, order: 311),
  (key: "rl.s_oracle", tex: "s_t^{\\mathrm{oracle}}", description: "Oracle-only state used for labels, upper bounds, and evaluation.", thesis_list: true, order: 320),
  (key: "rl.target_reward", tex: "r_t^e", description: "Target-specific immediate reward at rollout step t.", thesis_list: true, order: 330),
  (key: "rl.return_h", tex: "G_{t,e}^{(h)}", description: "Target-conditioned return from rollout step t over requested residual horizon h.", thesis_list: true, order: 340),
  (key: "rl.qh", tex: "Q_{\\theta}(\\cdot,\\cdot,\\cdot,h)", description: "Horizon-conditioned candidate-value family represented by one shared scorer.", thesis_list: true, order: 350),
  (key: "rl.conditional_q", tex: "Q_{\\theta}(s_t,e,i,h)", description: "Action-mask-independent candidate value emitted by the horizon-conditioned scorer.", thesis_list: true, order: 351),
  (key: "rl.feasibility_logits", tex: "\\ell_{t,i}^{\\mathrm{feas}}", description: "Physical or observed feasibility logit emitted by the scorer's feasibility head.", thesis_list: true, order: 352),
  (key: "rl.coral_q_edge", tex: "e_k^Q", description: "Fixed continuous fitted-Q boundary between adjacent CORAL classes.", thesis_list: true, order: 353),
  (key: "rl.coral_q_value", tex: "u_k^Q", description: "Fixed continuous-Q representative used to decode one CORAL class.", thesis_list: true, order: 354),
  (key: "rl.coral_q_label", tex: "c_n^Q", description: "Ordinal class assigned to one continuous fitted-Q target.", thesis_list: true, order: 355),
  (key: "rl.gamma", tex: "\\gamma", description: "Return discount factor.", thesis_list: true, order: 360),
  (key: "rl.H", tex: "H", description: "Planning or rollout horizon length.", thesis_list: true, order: 370),
  (key: "rl.H_max", tex: "H_{\\mathrm{max}}", description: "Maximum residual horizon admitted by a scorer/data contract.", thesis_list: true, order: 371),
  (key: "rl.requested_horizon", tex: "h", description: "Scalar residual horizon requested for one scorer query; it must satisfy 1 <= h <= b_t <= H_max.", thesis_list: true, order: 372),
  (key: "rl.candidate_row_mask", tex: "m_{t,i}^{\\mathrm{cand}}", description: "Materialized candidate row versus structural padding.", thesis_list: true, order: 381),
  (key: "rl.action_mask", tex: "m_{t,i}^{\\mathrm{act}}", description: "Authoritative physically valid action support.", thesis_list: true, order: 382),
  (key: "rl.q_label_mask", tex: "m_{t,i}^{Q,h}", description: "Availability of a finite factual value target for candidate i at requested horizon h.", thesis_list: true, order: 383),
  (key: "rl.feasibility_label_mask", tex: "m_{t,i}^{F}", description: "Availability of a trustworthy feasibility label for candidate i.", thesis_list: true, order: 384),
  (key: "rl.successor_mask", tex: "m_t^{\\mathrm{succ}}", description: "Availability of a factual successor backup for transition t.", thesis_list: true, order: 385),
  (key: "rl.source_role", tex: "\\zeta_{t,i}^{\\mathrm{src}}", description: "Categorical actor-oracle source-provenance role for candidate evidence.", thesis_list: true, order: 386),
  (key: "rl.invalid_reason", tex: "\\rho_{t,i}", description: "Invalid-action reason code for candidate i at rollout step t.", thesis_list: true, order: 390),
  (key: "rl.target", tex: "e_t", description: "Selected target entity at rollout step t.", thesis_list: true, order: 400),
  (key: "rl.budget", tex: "b_t", description: "Remaining acquisition budget at rollout step t.", thesis_list: true, order: 410),
  (key: "rl.acquisition_cost", tex: "C(\\tau)", description: "Acquisition cost of a selected trajectory.", thesis_list: true, order: 420),
  (key: "shape.Nq", tex: "N_q", description: "Number of candidate views in a candidate table.", thesis_list: false, order: 430),
  (key: "shape.K", tex: "K", description: "Number of ordinal bins or discrete levels when used in scorer losses.", thesis_list: false, order: 440),
  (key: "scene.ray_memory_t", tex: "\\boldsymbol{M}_t^{\\mathrm{ray}}", description: "Sparse actor-visible ray-aware memory separating occupied, free, and unknown support at step t.", thesis_list: true, order: 450),
  (key: "scene.scene_memory_t", tex: "\\boldsymbol{\\Phi}_t^{\\mathrm{scene}}", description: "Composite actor-visible scene-memory descriptor queried by the finite-candidate value model.", thesis_list: true, order: 480),
  (key: "obs.dino_point_bank_t", tex: "\\boldsymbol{F}_t^{\\mathrm{DINO@pt}}", description: "Visibility-gated logged DINO feature bank attached to semidense or fused world points.", thesis_list: true, order: 460),
  (key: "obs.point_tokens_t", tex: "\\boldsymbol{X}_t^{\\mathrm{pt}}", description: "Point-token set combining geometry, support, uncertainty, history, and optional compressed logged descriptors.", thesis_list: true, order: 470),
  (key: "scene.evl_local", tex: "\\boldsymbol{E}_0^{\\mathrm{EVL-local}}", description: "Root local EVL evidence field used for target/candidate support reads.", thesis_list: true, order: 490),
  (key: "scene.evl_support_frac", tex: "\\omega_{t,i}^{\\mathrm{EVL}}", description: "Candidate or target-query fraction supported by the root EVL voxel extent.", thesis_list: true, order: 500),
  (key: "scene.evl_support_token", tex: "\\boldsymbol{g}_{t,i}^{\\mathrm{EVL}}", description: "Pooled local EVL evidence token for a target, candidate frustum, or target-candidate intersection query.", thesis_list: true, order: 510),
  (key: "scene.target_support_pool", tex: "\\boldsymbol{g}_e^{\\mathrm{tgt}}", description: "Pooled target-support descriptor for the selected target hypothesis.", thesis_list: true, order: 520),
  (key: "scene.frustum_support_pool", tex: "\\boldsymbol{g}_{t,i}^{\\mathrm{fr}}", description: "Candidate-frustum support descriptor pooled from actor-visible scene memory.", thesis_list: true, order: 530),
  (key: "scene.target_frustum_pool", tex: "\\boldsymbol{g}_{t,e,i}^{\\cap}", description: "Pooled descriptor over the intersection between target support and candidate frustum support.", thesis_list: true, order: 540),
  (key: "scene.ray_query_ti", tex: "\\boldsymbol{g}_{t,i}^{\\mathrm{ray}}", description: "Candidate-conditioned ray query over occupied, free, unknown, hit, target-support, and uncertainty summaries.", thesis_list: true, order: 550),
  (key: "scene.render_query", tex: "\\operatorname{RenderQuery}", description: "Abstract query operator that summarizes scene memory in a candidate camera/frustum without introducing fresh counterfactual RGB features.", thesis_list: true, order: 560),
  (key: "spatial.ref_pose", tex: "r_t", description: "Reference pose for candidate-relative descriptor construction at decision step t.", thesis_list: true, order: 565),
  (key: "spatial.ref_candidate_transform", tex: "\\boldsymbol{T}_{r_t,i}^{\\mathrm{rel}}", description: "Relative transform from the reference pose r_t to candidate camera i.", thesis_list: true, order: 568),
  (key: "spatial.candidate_pose_feat", tex: "\\boldsymbol{h}_{t,i}^{\\mathrm{pose}}", description: "Relative/local candidate pose descriptor derived from a reference pose rather than raw world coordinates.", thesis_list: true, order: 570),
  (key: "spatial.candidate_target_rel_feat", tex: "\\boldsymbol{h}_{t,e\\mid i}^{\\mathrm{rel}}", description: "Candidate-target relation descriptor in the candidate/query local frame.", thesis_list: true, order: 580),
  (key: "spatial.relation_rpe", tex: "\\boldsymbol{e}_{a\\mid i}^{\\mathrm{rel}}", description: "Query-local relative positional embedding for target, history, support, or candidate relations.", thesis_list: true, order: 590),
  (key: "spatial.target_obb_scale", tex: "r_e", description: "Geometric-mean target-proxy scale derived from the target OBB semi-axis lengths.", thesis_list: true, order: 592),
  (key: "spatial.target_frame_motion_direction", tex: "\\widehat{\\boldsymbol{\\delta}}_{j,t}^{e}", description: "Unit factual selected-camera displacement expressed in target-object coordinates for rollout j and step t.", thesis_list: true, order: 594),
  (key: "spatial.target_frame_view_direction", tex: "\\widehat{\\boldsymbol{v}}_{j,t}^{e}", description: "Unit selected-camera forward optical axis expressed in target-object coordinates.", thesis_list: true, order: 596),
  (key: "spatial.target_frame_frustum", tex: "\\mathcal{F}_{j,t}^{e}", description: "Front-facing target-proxy surface directions that project inside the calibrated selected-camera image.", thesis_list: true, order: 598),
  (key: "spatial.target_frame_frustum_fraction", tex: "\\kappa_{j,t}^{e}", description: "Fraction of the target-centred proxy sphere geometrically supported by one selected calibrated frustum.", thesis_list: true, order: 599),
  (key: "spatial.frustum_solid_angle", tex: "\\Omega_{j,t}^{\\mathrm{FOV}}", description: "Intrinsic solid angle of one calibrated selected-camera pinhole field of view.", thesis_list: true, order: 601),
  (key: "rl.rollout_index", tex: "j", description: "Factual rollout-chain index used to preserve common trajectory heritage across selected steps.", thesis_list: true, order: 245),
  (key: "model.target_token", tex: "\\boldsymbol{h}_e^{\\mathrm{tgt}}", description: "Learned selected-target token built from the actor-visible target descriptor and scene support.", thesis_list: true, order: 600),
  (key: "model.candidate_row", tex: "\\boldsymbol{x}_{t,i}", description: "Per-candidate row feature assembled from pose, relation, support, validity, provenance, and history descriptors.", thesis_list: true, order: 610),
  (key: "model.history_pose_feature", tex: "\\boldsymbol{p}_{t,j}^{\\mathrm{hist}}", description: "Factual trajectory pose at time j encoded from the current camera at decision state t.", thesis_list: true, order: 612),
  (key: "model.history_relative_age", tex: "a_{t,j}^{\\mathrm{hist}}", description: "Normalized relative age of selected pose j at decision state t; the immediate predecessor has age zero.", thesis_list: true, order: 614),
  (key: "model.history_token", tex: "\\boldsymbol{h}_t^{\\mathrm{hist}}", description: "Fixed-width causal selected-pose history token supplied to scorer state fusion.", thesis_list: true, order: 616),
  (key: "entity.endpoint_gain", tex: "J_e^{(H)}", description: "Endpoint reconstruction gain for target e over horizon H.", thesis_list: true, order: 620),
  (key: "entity.log_gain", tex: "J_{e,\\mathrm{log}}^{(H)}", description: "Log-scale endpoint reconstruction gain for target e.", thesis_list: true, order: 630),
  (key: "entity.lookahead_headroom", tex: "\\Delta_{\\mathrm{look}}", description: "Gain available to an oracle lookahead policy beyond one-step selection.", thesis_list: true, order: 640),
  (key: "entity.q_recovery", tex: "\\eta_Q", description: "Fraction of the learned-myopic-to-oracle-lookahead endpoint gap closed by the Q policy.", thesis_list: true, order: 650),
  (key: "rl.candidate_table", tex: "\\mathcal{Q}_t", description: "Finite candidate-action table at rollout step t.", thesis_list: true, order: 730),
  (key: "rl.candidate_qti", tex: "q_{t,i}", description: "Candidate action row i at rollout step t; it carries one proposed endpoint pose.", thesis_list: true, order: 731),
  (key: "spatial.candidate_camera_frame", tex: "c_{t,i}^{\\mathrm{cand}}", description: "Prospective camera frame carried by candidate action row i at decision step t.", thesis_list: true, order: 732),
  (key: "spatial.trajectory_camera_frame", tex: "c_t^{\\mathrm{traj}}", description: "Factual camera frame on the realised trajectory at decision step t.", thesis_list: true, order: 733),
  (key: "obs.depth", tex: "\\boldsymbol{D}", description: "Depth observation sequence.", thesis_list: true, order: 670),
  (key: "obs.face_normal", tex: "\\boldsymbol{n}", description: "Per-point or per-face normal observation.", thesis_list: true, order: 680),
  (key: "obs.img_rgb", tex: "\\boldsymbol{I}^{\\mathrm{rgb}}", description: "RGB image observation.", thesis_list: true, order: 690),
  (key: "obs.points_cf", tex: "\\mathcal{P}^{\\mathrm{cf}}", description: "Counterfactual point observation.", thesis_list: true, order: 700),
  (key: "obs.points_semi", tex: "\\mathcal{P}^{\\mathrm{semi}}", description: "Semi-dense observed point set.", thesis_list: true, order: 710),
  (key: "obs.points_t", tex: "\\mathcal{P}_t", description: "Point set available at rollout step t.", thesis_list: true, order: 720),
  (key: "rl.exact_q2_target", tex: "y_t^{(2,\\mathrm{exact})}", description: "Exact two-step fitted-Q control using factual dense successor one-step rewards.", thesis_list: true, order: 732),
  (key: "rl.q2_recursion_error", tex: "\\varepsilon_t^{(2)}", description: "Absolute learned-recursion target error against the exact two-step control.", thesis_list: true, order: 734),
  (key: "vin.field_v", tex: "\\boldsymbol{F}_v", description: "Learned value field evaluated at v.", thesis_list: true, order: 740),
)

#for entry in aria-notation-symbols [
  #metadata(entry) <aria-notation-symbol>
]
