#let rl = (
  // RL state / observation / reward / return.
  s: $s$,
  o: $o$,
  a: $a$,
  r: $r$,
  G: $G$,
  Q: $Q$,
  V: $V$,
  pi: $pi$,
  A: $A$,
  H: $H$,
  gamma: $gamma$,
  mdp_nbv: $cal(M)_"NBV"$,
  action_set: $cal(A)(s_t)$,
  action_set_t: $cal(A)_t$,
  transition: $T$,
  s_hist: $s_t^"hist"$,
  s_off: $s_t^"off"$,
  s_obs: $s_t^"obs"$,
  s_cf0: $s_t^"cf0"$,
  s_cf0_next: $s_(t+1)^"cf0"$,
  s_cf_geom: $s_t^"cf+"$,
  s_oracle: $s_t^"oracle"$,
  state_emb: $bold(h)_t$,
  reward_target: $r_t^e$,
  return_h: $G_t^((H))$,
  qh: $Q_H$,
  qh_theta: $Q_(H,theta)$,
  qh_target: $Q_(H,theta^-)$,
  validity_mask: $m_(t,i)$,
  invalid_reason: $rho_(t,i)$,
  delta: $delta$,
  rho: $rho$,
  z: $z$,
  // Pose / persistent memory / optional entity memory / budget.
  x: $bold(x)$,
  m: $bold(m)$,
  e: $bold(e)$,
  b: $b$,
  acquisition_cost: $C(tau)$,
  candidate_table: $cal(Q)_t$,
  candidate_set: $cal(Q)_t$,
  candidate_token: $bold(u)_(t,i)$,
  candidate_qti: $q_(t,i)$,
  candidate_mask: $bold(m)_t$,
  invalid_reasons: $bold(rho)_t$,
  candidate_features: $bold(X)_t^"cand"$,
  q_weight: $bold(w)_Q$,
  target: $e_t$,
  budget: $b_t$,
  selected_action_theta: $a_t^theta$,
  td_target: $y_t$,
  q_loss: $cal(L)_Q (theta)$,
)
