#import "../../../shared/macros.typ": *
#import "../../draft_markers.typ": *

== Related Work

Classical active perception establishes that sensing actions and perceptual inference must be designed jointly, while three-dimensional view planning supplies the finite generate--score--select abstraction used in this thesis @ActivePerception-bajcsy1988 @ActiveVision-aloimonos1988 @ViewPlanningSurvey-scott2003. Receding-horizon and submodular formulations further explain why finite lookahead and greedy comparators are informative under particular utility assumptions @RecedingHorizonNBV-bircher2016 @SubmodularNBV-lauri2020. They do not establish approximation guarantees for target-specific RRI, whose utility changes with target matching, occlusion, candidate regeneration, and reconstruction support. The thesis gap is therefore not another generic view-planning loop, but a bounded test of whether a target-quality objective exhibits non-myopic structure under explicitly fixed support.

Quality-driven NBV replaces geometric coverage proxies with reconstruction-quality supervision. VIN-NBV is the closest precedent because it ranks sampled candidates using oracle RRI rather than visibility alone @VIN-NBV-frahm2025. PB-NBV contributes efficient finite projection-based proposal and scoring; it is not evidence for continuous control @PB-NBV-jia2025. These methods do not establish target-cropped finite-horizon value under an Aria-native actor/oracle separation. ARIA-NBV therefore uses a VIN-style learned one-step scorer as a control and asks separately whether finite-horizon endpoint gain exceeds that myopic decision rule.

Target- and object-aware NBV research shows why scene-wide utility can hide the reconstruction needs of a particular entity. Object-centric NBV motivates conditioning view utility on a designated object, while OANBV and ObjViewBench contribute visibility, feasibility, occlusion, and target-difficulty analyses @ObjectCentricNBV-jeong2026 @OANBV-hu2026 @ObjViewBench-pan2026. They do not justify the residual $Q_H$ architecture or establish target-specific RRI headroom. The resulting thesis gap is a target task whose identity is oracle-defined for supervision, whose descriptor is actor-visible for policy input, and whose endpoint quality is evaluated on the matched target crop.

Project Aria defines the calibrated multimodal egocentric sensing regime, ASE supplies synthetic trajectories, annotations, and ground-truth geometry, and EFM3D/EVL supplies local actor-visible spatial evidence and object hypotheses @projectaria-engel2023 @ProjectAria-ASE-2025 @EFM3D-straub2024. This stack enables controlled counterfactual labels but does not itself define an NBV objective or confer oracle information on the actor. In ARIA-NBV, meshes and ground-truth boxes remain label and evaluation assets; the learned policy must operate from logged observations, counterfactually accumulated actor evidence, and an actor-visible target descriptor.

Offline value learning and finite-action rollout methods provide warnings and controls for the planning problem. Double DQN motivates separating successor-action selection from evaluation, while IQL, CQL, and BCQ show why unsupported actions and out-of-distribution bootstrapping require explicit treatment @DoubleDQN-vanHasselt2015 @IQL-kostrikov2021 @CQL-kumar2020 @BCQ-fujimoto2019. These works do not remove the need for a domain-specific reward, candidate support audit, or oracle re-evaluation. The thesis consequently treats the finite candidate table and hard mask as part of the estimand, logs rollout lineage, and evaluates selected trajectories by endpoint target quality rather than predicted value alone.

Set and geometric learning provide the relevant inductive biases for scoring a finite unordered candidate table. Deep Sets supplies a pooled symmetry baseline, Set Transformer supplies masked candidate interaction, and geometric deep learning frames the choice of equivariance as a property of the input--output map @DeepSets-zaheer2017 @SetTransformer-lee2019 @GeometricDeepLearning-bronstein2021. These sources motivate row-equivariant scoring, mask isolation, and explicit local frames; they do not determine which representation or head will succeed. Point, sparse, recurrent, spherical-harmonic, DINO-on-point, and residual-head variants therefore remain hypotheses or exploratory ablations until implemented and evaluated.

Continuous policies, hierarchical target-then-pose control, radiance fields, and Gaussian Splatting define useful boundaries rather than core evidence. GenNBV and Hestia motivate continuous and hierarchical bridges @GenNBV-chen2024 @Hestia-lu2026. ActiveNeRF, FisherRF, Next Best Sense, and Gaussian Splatting contribute uncertainty objectives or representation families @ActiveNeRF-pan2022 @FisherRF-jiang2024 @NextBestSense-strong2024 @GaussianSplatting-kerbl2023; Gaussian Splatting does not provide target-aware utility by itself. These bridges are discussed only where they clarify a limitation of the finite-candidate protocol or motivate future work.
