#import "../../../shared/macros.typ": *
#import "../../draft_markers.typ": prune_todo, validation_todo

== Related Work

#prune_todo(
  [Replace catalogue-style architecture paragraphs with a smaller claim-by-claim synthesis: what each work establishes, which assumption differs here, and which concrete ARIA-NBV design or comparison follows.],
  source: [this section, especially the representation and architecture surveys],
  gate: [every retained citation has a stated argumentative role rather than membership in a list],
)

#validation_todo(
  [Add a structured evidence-comment block beside each claim-bearing paragraph, mapping every cited bibliography key to the exact local TeX or PDF locator used to support that claim.],
  source: [docs/references.bib; docs/references-qh.bib; docs/literature/tex-src],
  gate: [the citation-provenance audit reports no unsupported or unlocated literature claims],
)

Classical active perception establishes that sensing actions and inference must be designed jointly, while three-dimensional view planning supplies the finite generate--score--select abstraction used here @ActivePerception-bajcsy1988 @ActiveVision-aloimonos1988 @ViewPlanningSurvey-scott2003. Receding-horizon and submodular formulations explain why lookahead and greedy comparators can be informative under specific utility assumptions @RecedingHorizonNBV-bircher2016 @SubmodularNBV-lauri2020. They do not establish such guarantees for target-specific RRI, whose value depends on the evaluated target, current reconstruction support, and admissible candidates. This thesis therefore tests non-myopic headroom empirically under fixed support rather than assuming it from generic coverage objectives.

Quality-driven NBV replaces geometric coverage proxies with reconstruction-quality supervision. VIN-NBV is the closest precedent because it ranks sampled candidates using oracle RRI rather than visibility alone, while PB-NBV contributes efficient finite projection-based proposals @VIN-NBV-frahm2025 @PB-NBV-jia2025. Neither establishes target-cropped finite-horizon value under an Aria-native actor/oracle separation. ARIA-NBV consequently uses VIN-style one-step scoring as a myopic control and asks separately whether bounded lookahead improves endpoint target quality.

Target- and object-aware NBV shows why scene-wide utility can conceal the reconstruction needs of one entity. Object-centric NBV motivates conditioning view utility on a designated object, while OANBV and ObjViewBench contribute visibility, feasibility, occlusion, and target-difficulty analyses @ObjectCentricNBV-jeong2026 @OANBV-hu2026 @ObjViewBench-pan2026. The current ARIA-NBV data generator does not solve actor-visible target discovery: it samples geometry-valid GT OBB rows as target tasks and evaluates their target crops. Observed or predicted target records are therefore a separate requirement for learned-policy claims, not an implemented consequence of target-specific supervision.

Project Aria defines the calibrated multimodal egocentric sensing regime, ASE supplies synthetic trajectories and GT geometry, and EFM3D/EVL supplies local actor-visible spatial evidence and object hypotheses @projectaria-engel2023 @ProjectAria-ASE-2025 @EFM3D-straub2024. This stack enables controlled counterfactual labels but does not itself define an NBV objective or make oracle information actor-visible. Meshes, GT boxes, and all-candidate renders remain supervision and evaluation assets; candidate selection must ultimately use logged observations, accumulated selected-view evidence, and an observed or predicted target record.

Offline value learning does not require online environment interaction. Fitted Q iteration estimates a greedy action-value function from a fixed transition batch through a sequence of supervised regression problems @FittedQIteration-ernst2005. For a bounded variable horizon, fixed-horizon TD defines a family of values in which the horizon-$h$ prediction bootstraps from horizon $h-1$ rather than from itself; the additional functions may share parameters and be updated in parallel @FixedHorizonTD-deAsis2020. Conditioning one shared approximator on the requested horizon follows the more general principle of conditioning value functions on an explicit task variable @UVFA-schaul2015. Double DQN is a possible selector/evaluator correction for overestimation in a learned successor maximum, not a prerequisite for offline learning or for the definition of a variable-horizon scorer @DoubleDQN-vanHasselt2015. CQL and BCQ remain relevant warnings that a max over learned values can select actions whose multi-step consequences are weakly supported by the offline behavior data @CQL-kumar2020 @BCQ-fujimoto2019.

Deep Sets and Set Transformer provide permutation-aware baselines for an unordered candidate table @DeepSets-zaheer2017 @SetTransformer-lee2019. These methods do not replace the domain contract: invalid actions remain hard-masked, candidate support is reported, and every selected trajectory is re-evaluated by endpoint target quality rather than accepted on predicted value alone.

Geometric representation learning supplies a hierarchy of inductive biases rather than one mandatory backbone. Query-local relative encoding can remove nuisance global coordinates while preserving target, frustum, and motion geometry @zhou2023query. PointNeXt, Point Transformer, KPConv, and sparse convolutions offer coordinate-bearing encoders when explicit point or ray-memory summaries become insufficient @PointNeXt-qian2022 @PointTransformerV3-wu2024 @KPConv-thomas2019 @MinkowskiEngine-choy2019. EGNN, SE(3)-Transformer, and GATr provide stronger equivariant alternatives @EGNN-satorras2021 @SE3Transformer-fuchs2020 @GATr-brehmer2023, but exact equivariance is not assumed beneficial for a gravity-aligned, metric, egocentric task; it remains an ablation against simpler local-frame features.

Broader scene memories address a different limitation from candidate interaction. GenNBV distinguishes occupied, free, and unknown grid state, Hestia records directional visibility, SceneScript extracts broad layout and object structure from Aria-style semidense input, and object-aware 3D Gaussian Splatting couples renderable primitives with target membership @GenNBV-chen2024 @Hestia-lu2026 @SceneScript-avetisyan2024 @ObjectCentricNBV-jeong2026. ARIA-NBV uses these works to define representation hypotheses and diagnostics; it does not import their rewards, action spaces, or performance claims into the finite-candidate target-RRI experiment.
