#import "../../../shared/macros.typ": *

== Related Work

ARIA-NBV sits between classical view planning, learned reconstruction-quality scoring, and egocentric scene understanding @ActivePerception-bajcsy1988 @ActiveVision-aloimonos1988. Classical @next-best-view work formalizes the generate-score-select loop for three-dimensional inspection and reconstruction @NBVSystem-banta2000 @RecedingHorizonNBV-bircher2016 @ShadowcastingNBV-batinovic2022, while submodular and adaptive-submodular active-sensing results explain why greedy policies can be strong when the utility has diminishing returns @NemhauserSubmodular1978 @SubmodularNBV-lauri2020 @ViewPlanningSurvey-scott2003 @KrauseSensorPlacement2008 @AdaptiveSubmodularity-golovin2011. This thesis uses that lineage as a baseline discipline rather than as a theorem claim: target-specific @relative-reconstruction-improvement depends on masks, object matching, candidate regeneration, occlusion, and changing support, so coverage-style approximation guarantees are treated as motivation for greedy controls, not as properties of the ARIA objective.

The closest objective precedent is VIN-NBV, which learns to rank sampled candidate views by oracle @relative-reconstruction-improvement instead of by pure coverage @VIN-NBV-frahm2025. ARIA-NBV keeps that reconstruction-quality signal but changes both the state and the unit of evaluation. The actor-visible state comes from Project Aria-style egocentric streams and @aria-synthetic-environments assets @projectaria-engel2023 @ProjectAria-ASE-2025, and the thesis target is @target-specific-rri rather than only scene-level gain. CORAL-style ordinal learning is therefore useful for a calibrated one-step scorer, but it is a control for label reliability and ranking, not the whole finite-horizon planning result @CORAL-cao2019.

Project Aria, @aria-synthetic-environments, and @egocentric-foundation-model-3d supply the substrate for this thesis. Project Aria defines the multimodal egocentric sensor regime and calibration assumptions, @aria-synthetic-environments provides mesh-supervised synthetic trajectories and annotations, and EFM3D/@egocentric-voxel-lifting contributes actor-visible local voxel evidence, lifted image features, and object hypotheses @projectaria-engel2023 @ProjectAria-ASE-2025 @EFM3D-straub2024. The thesis does not treat @egocentric-voxel-lifting as a complete world model. Its role is local target/support evidence; broader scene memory is represented through semi-dense or fused point support, ray-aware occupied/free/unknown memory, and, if needed, visibility-gated point-attached feature banks.

Coverage and information-based @next-best-view methods provide useful diagnostic channels but not the primary reward. SCONE and MACARONS estimate surface visibility or coverage from learned scene representations, while ActiveNeRF, FisherRF, and Next Best Sense use information gain and uncertainty in radiance-field or Gaussian-splatting settings @SCONE-guedon2022 @MACARONS-guedon2023 @ActiveNeRF-pan2022 @FisherRF-jiang2024 @NextBestSense-strong2024. ARIA-NBV can adopt support, overlap, uncertainty, and directional-history features from this family, but the thesis compares those proxies against @target-specific-rri rather than replacing the mesh-supervised label. Object-centric, occlusion-aware, and benchmark work similarly motivates target-aware utility and semantic failure analysis, while remaining a bridge once the mesh/oracle target protocol is stable @ObjectCentricNBV-jeong2026 @OANBV-hu2026 @ObjViewBench-pan2026 @GaussianSplatting-kerbl2023.

Continuous-policy @next-best-view papers define an important boundary for the thesis. GenNBV learns a generalizable continuous policy for active reconstruction, PB-NBV emphasizes efficient projection-based candidate scoring, and Hestia introduces a hierarchical target-then-pose formulation with directional observability @GenNBV-chen2024 @PB-NBV-jia2025 @Hestia-lu2026. These works motivate later actor-critic, projection-shortlist, and hierarchy experiments. The core thesis remains narrower: finite candidate tables over @aria-synthetic-environments snippets, oracle target labels from @ground-truth-target-evaluation, and a masked #symb.rl.qh model whose selected actions are re-evaluated by the same oracle.

The planned value model also borrows structure from set and geometric learning. Deep Sets gives a pooled symmetry baseline for unordered candidate or point sets; Set Transformer supplies masked candidate-candidate interaction as an ablation; and query-centric trajectory forecasting motivates local relative positional encodings without importing a motion-forecasting decoder @DeepSets-zaheer2017 @SetTransformer-lee2019 @zhou2023query. Geometric deep learning frames the broader design question as matching model symmetries to the output map, not making the whole system invariant @GeometricDeepLearning-bronstein2021. For ARIA-NBV this means candidate-row permutation equivariance for #symb.rl.qh scores, candidate-to-state queries before candidate-candidate self-attention, mask isolation for invalid rows, explicit target/current/candidate frames, and gravity-aware rather than full rotation-invariant features. The dedicated theory treatment in @sec:thesis-geometric-learning-theory turns those literature roles into the architecture ladder and acceptance tests.

Point and sparse scene encoders are best treated as representation ablations after the simpler support contract is measured. Point Transformer, PointNeXt, Point Transformer V3, KPConv, and sparse-convolutional encoders offer local geometric interaction, density handling, scalability, or sparse-volume computation @point-transformer-zhao2021 @PointNeXt-qian2022 @PointTransformerV3-wu2024 @KPConv-thomas2019 @MinkowskiEngine-choy2019. They become relevant if compact target, frustum, support, and lifted-feature pools leave a measurable bottleneck for @target-specific-rri ranking or finite-horizon #symb.rl.qh. They are not first-line replacements for EFM3D because a thesis backbone must still provide actor-visible OBB hypotheses and reusable scene conditioning.

Finally, offline and recurrent decision-modeling papers inform the training and ablation ladder without changing the problem definition. Double DQN and dueling heads motivate selector/evaluator separation and value/advantage structure for finite candidate tables @DoubleDQN-vanHasselt2015 @DuelingDQN-wang2016. IQL, CQL, and BCQ motivate explicit support constraints and skepticism about out-of-distribution bootstrapping, not an immediate switch away from the finite-candidate replay contract @IQL-kostrikov2021 @CQL-kumar2020 @BCQ-fujimoto2019. Trajectory Transformer, Decision Transformer, and Gumbel-Top-k provide vocabulary for sequence modeling, return conditioning, and stochastic branch generation only after the target/candidate/mask/evaluation contract is shared with the simpler baselines @TrajectoryTransformer-janner2021 @DecisionTransformer-chen2021 @GumbelTopK-kool2019. Deja View suggests a bounded weight-tied refinement ablation for candidate-context tokens, but not a claim that reconstruction-loop recurrence transfers directly to ARIA-NBV planning @dejaviewloopingtransformersburzio2026.

=== Literature Roles and Boundaries

*VIN-NBV and ordinal scoring.* This family provides the closest label precedent: oracle @relative-reconstruction-improvement, one-step candidate ranking, and CORAL-style calibration. ARIA-NBV adopts those elements as controls for target-specific label quality and scorer behavior, while treating finite-horizon lookahead as a separate question rather than stopping at myopic ranking.

*Project Aria, @aria-synthetic-environments, and @egocentric-voxel-lifting.* This stack defines the actor-visible substrate through egocentric sensing, calibration, semi-dense support, local voxel evidence, and OBB hypotheses. Its boundary is equally important: meshes and target crops remain supervision and evaluation tools, not part of the online actor-visible state.

*Coverage, uncertainty, and information-gain methods.* SCONE, MACARONS, FisherRF, and related radiance-field or Gaussian-splatting approaches contribute support, overlap, uncertainty, information-gain, and directional-novelty signals. In this thesis those quantities are diagnostic channels or candidate-token features, not replacements for @target-specific-rri as the primary objective.

*Set and geometric models.* Deep Sets, Set Transformer, and geometric-learning arguments provide the structural prior for finite candidate tables: permutation-aware scoring, masked attention, local relative encodings, and explicit symmetry tests. ARIA-NBV uses this family to shape #symb.rl.qh controls before escalating to heavier point or sparse backbones.

*Continuous, hierarchical, and recurrent bridges.* GenNBV, Hestia, and Deja View motivate later bridge experiments in continuous control, hierarchical decomposition, or bounded refinement. They remain downstream ablations until finite-candidate labels, invalid-action masks, and replay-based evaluation are trustworthy.
