#import "../draft_markers.typ": development_only
#import "../experiment_data.typ": load-scientific-report, report-value, report-figure-path, format-report-value

#development_only(() => {
  let s2-report = load-scientific-report(
    "/typst/thesis/data/s2-rollout-pilot/report.json",
    evidence-status: "pilot",
  )
  let source-sample-count = report-value(s2-report, "s2.quantity.s01.source-sample-count")
  let source-snippet-count = report-value(s2-report, "s2.quantity.s01.source-snippet-count")
  let source-scene-count = report-value(s2-report, "s2.quantity.s01.source-scene-count")
  let target-count = report-value(s2-report, "s2.quantity.s01.target-count")
  let rollout-count = report-value(s2-report, "s2.quantity.s01.rollout-count")
  let selected-step-count = report-value(s2-report, "s2.quantity.s01.selected-step-count")
  let movement-count = report-value(s2-report, "s2.quantity.s01.movement-count")
  let view-count = report-value(s2-report, "s2.quantity.s01.view-direction-count")
  let frustum-count = report-value(s2-report, "s2.quantity.s01.frustum-count")
  let mean-solid-angle = report-value(s2-report, "s2.quantity.s01.mean-frustum-solid-angle")
  let mean-proxy-fraction = report-value(s2-report, "s2.quantity.s01.mean-proxy-surface-fraction")
  let union-proxy-fraction = report-value(s2-report, "s2.quantity.s01.union-proxy-surface-fraction")

  [
    = Development Pilots

    == Candidate-Family Support

    // Evidence: contents/evidence/candidate_target_orbit_mvp/manifest.json
    // schema aria-nbv-candidate-target-orbit-mvp-v3; the exact manifest digest is checked in repository tests.
    #figure(
      align(center, image(
        "../../../contents/evidence/candidate_target_orbit_mvp/candidate-centers.png",
        width: 100%,
      )),
      caption: [Attempted candidate centres from a two-scene, two-state real-data method audit. Each state is centred on its factual expansion pose, yaw-aligned to the oracle-evaluation target with world Z-up, and divided by its current three-dimensional target distance. The cross marks the expansion/root pose, the stars mark the two oracle task target centres, colour denotes proposal family, and marker shape denotes actor-valid or selected status. The figure diagnoses proposal geometry under the `v0_gt_input` target protocol; it is neither a population estimate nor evidence of actor-visible target discovery or policy quality.],
    ) <fig:candidate-target-orbit-pilot-support>

    The target-orbit challenger adds attempted support on both target-relative
    sides in this bounded pilot, while pruning still leaves invalid rows and one
    configured family/state pair without actor-valid support. The associated
    immutable evidence manifest records the common-frame reducer, store-manifest
    hashes, expected state index, committed reduced candidate rows, resolved
    challenger profile, reproduction commands, metric denominators, and plot
    hashes. No frame-mixed side-balance or orbit-span values are used. The
    interactive evidence and Streamlit view can optionally add short arrows for
    the valid candidates' camera optical axes; the static thesis figure omits
    them to preserve legibility.

    == Target-Frame $cal(S)^2$ Diagnostics

    The following frozen figures are generated by the same Python reporting and plotting owners as the stored-rollout application. For the selected real-data shard, the report records these support counts: source samples #format-report-value(source-sample-count.value), snippets #format-report-value(source-snippet-count.value), scenes #format-report-value(source-scene-count.value), targets #format-report-value(target-count.value), retained rollout chains #format-report-value(rollout-count.value), and selected steps #format-report-value(selected-step-count.value). It remains pilot evidence: its purpose is to validate the representation and reporting contract, not to estimate policy quality. The two point-direction views contain #format-report-value(movement-count.value) factual displacements and #format-report-value(view-count.value) factual optical axes. Colour denotes rollout-chain identity, marker shape denotes decision-step identity, and the sphere heat map is computed from the complete equal-solid-angle count grid rather than from the bounded incidence overlay.

    #figure(
      align(center, image(
        report-figure-path(s2-report, "s2.figure.s01.movement"),
        width: 82%,
      )),
      caption: [Target-frame $cal(S)^2$ movement directions from the frozen pilot report. This view records how the camera moved; it is not a visibility measurement.],
    ) <fig:s2-pilot-movement>

    #figure(
      align(center, image(
        report-figure-path(s2-report, "s2.figure.s01.view-direction"),
        width: 82%,
      )),
      caption: [Target-frame $cal(S)^2$ selected-camera optical-axis directions from the same frozen pilot report. This view records where the camera pointed; it is distinct from both camera motion and calibrated surface support.],
    ) <fig:s2-pilot-view-direction>

    The calibrated proxy diagnostic integrates #format-report-value(frustum-count.value) selected frusta. Their mean intrinsic field-of-view solid angle is #format-report-value(mean-solid-angle.value, digits: 3, unit: mean-solid-angle.unit). On the geometric-mean-scale proxy sphere, one view covers a mean fraction of #format-report-value(mean-proxy-fraction.value, digits: 3), while their union covers #format-report-value(union-proxy-fraction.value, digits: 3). These fractions express geometric potential support under the proxy and front-facing tests; they exclude true target shape, depth ordering, and scene occlusion.

    #figure(
      align(center, image(
        report-figure-path(s2-report, "s2.figure.s01.frustum"),
        width: 70%,
      )),
      caption: [Calibrated selected-frustum support on the target-centred proxy sphere. The surface heat map is the complete equal-solid-angle coverage field; overlaid incidence samples preserve rollout and time heritage. This is not measured target-mesh visibility.],
    ) <fig:s2-pilot-frustum-support>
  ]
})
