#import "../../../shared/macros.typ": *
#import "../../../shared/symbols.typ": symb
#import "../../../shared/equations.typ": eqs

== State as an Information Contract

An NBV state contains exactly the information on which an action value may
depend. ARIA-NBV therefore
distinguishes three nested roles: logged evidence from the observed snippet,
causal evidence produced by actions that were actually selected, and privileged
quantities used only to construct or evaluate counterfactuals. ASE provides both
sensor-like streams and ground truth, whereas EFM3D transforms only logged image
evidence into a local 3D representation @ProjectAria-ASE-2025
@EFM3D-straub2024. Provenance and acquisition time determine information role
independently of file location and tensor shape.

// evidence:
// - @ProjectAria-ASE-2025 -> docs/contents/ase_dataset.qmd:216-225,257-260 (sensor-like streams and privileged GT products)
// - @EFM3D-straub2024 -> docs/literature/tex-src/arXiv-EFM3D/method.tex:1-42 (logged modalities, voxel lifting, and GT-supervised heads)

#figure(
  align(center, image(
    "../../figures/actor_oracle_boundary.pdf",
    width: 100%,
  )),
  caption: [Information roles in the offline experiment. The actor side contains calibrated logged observations, derived EFM3D evidence, an explicitly sourced target instruction, the selected-view prefix, remaining budget, candidates, and the hard action mask. The oracle side adds @ground-truth:short geometry, counterfactual renders, labels, and endpoint evaluation. Every stored field keeps its declared information role.],
) <fig:qh-actor-oracle-contract>

The boundary is also temporal. A render from an unselected candidate is a
counterfactual oracle query. After that candidate is selected, an observation
from its pose may enter the next state, but only under a declared acquisition
model: a real observation, an admitted sensor simulation, or a privileged mesh
render. Actor visibility requires both factual selection and an admitted source
role.

=== Logged Information State

The logged historic state #symb.rl.s_hist groups the evidence available before
any counterfactual acquisition:

$
  #eqs.rl.s_hist
$

Calibrated images and trajectory poses establish where and when evidence was
acquired. Semi-dense points provide sparse surface observations, and the EFM3D
field #symb.vin.field_v supplies a learned local representation. EFM3D lifts
posed image features into a finite gravity-aligned local volume
@EFM3D-straub2024. Absence from that volume denotes missing representation
support. Empty-space evidence requires measured rays, and pose feasibility
requires the geometric and motion checks defined later in this chapter.

// evidence:
// - @EFM3D-straub2024 -> docs/literature/tex-src/arXiv-EFM3D/method.tex:15-33, docs/literature/tex-src/arXiv-EFM3D/supplemental_text.tex:113-124 (calibrated lifting and finite local voxel extent)

Semi-dense points #symb.obs.points_semi retain uncertainty, timestamps, and
observing-camera lineage. EFM3D uses that lineage to distinguish surface samples
from free-space samples along measured rays @ProjectAria-ASE-2025
@EFM3D-straub2024. A point set supplies surface samples; camera rays additionally
supply free-space evidence. Missing surface samples carry no free-space meaning
without that lineage.

// evidence:
// - @ProjectAria-ASE-2025 -> docs/contents/ase_dataset.qmd:216-225 (MPS-style semi-dense points and uncertainty)
// - @EFM3D-straub2024 -> docs/literature/tex-src/arXiv-EFM3D/method.tex:15-33 (surface and free-space voxel evidence)

The target $e_t$ and remaining budget $b_t$ are task variables. They make the
value conditional, conceptually $Q(s_t,e_t,a_t)$, and distinguish two otherwise
identical observations posed with different requested objects or acquisition
budgets. In the present oracle task, $e_t$ is derived from a selected
@ground-truth:short box. A deployable task derives the target instruction from an
observation-side proposal and association path.

=== Causal Successor State

After an action is selected, the state may grow only with evidence generated by
that factual choice. The conceptual counterfactual actor state is

$
  #eqs.rl.s_cf0
$

and is read together with the ordered selected-view history:

#eqs.scene.actor_state_read

Here the root field is immutable, while the accumulated evidence may grow
only through selected observations. Candidate rows #symb.oracle.candidate_qti encode
possible poses and proposal provenance. Observations from those poses become
available only after selection. The hard mask #symb.rl.action_mask defines the
action set. Invalid-reason codes explain exclusions as diagnostic fields outside
the value-model input.
This separation prevents the proposal table from leaking the consequences it is
supposed to predict.

The implemented `S0-pose` baseline materializes the weaker state

$
  #eqs.rl.s_pose
$

It carries root evidence, target context, the current candidate table and mask,
the selected-pose prefix, and the remaining budget. This state represents the
actor's motion history. A geometry-enriched successor additionally retains what
the selected observations revealed:

$
  #eqs.rl.s_cf_geom
$

The implemented richer control is the intermediate carrier

$
  #eqs.rl.s_cf_gt_carrier
$

It retains calibrated depth only for selected actions. This makes the carrier
causal with respect to the selected path, while its mesh-rendered source keeps
the control privileged. Fusion into surface, free-space, uncertainty, and EFM3D
evidence defines the fuller geometry state. The implemented carrier isolates the
value of selected depth before that fusion.

More generally, the transition from $t$ to $t+1$ may consume only the observation
produced by $a_t$. RGB and EFM3D updates require the corresponding calibrated
image stream; depth updates the declared geometry channels.
#symb.rl.s_cf0 is an *information state* for value prediction. Its sufficiency
for the physical process is an empirical question: it is adequate only if it
preserves the distinctions needed to predict future target-specific return.

=== Oracle Augmentation

The oracle augments the causal state with quantities needed to answer
counterfactual questions:

$
  #eqs.rl.s_oracle
$

ASE provides per-frame metric @ground-truth:short depth aligned with RGB,
per-pixel instance identifiers, class mappings, and the scene trajectory. The
EFM3D release adds ASE OBB metadata and validation meshes for object-detection
and surface-reconstruction supervision @ProjectAria-ASE-2025
@EFM3D-straub2024. EFM3D uses depth to supervise occupancy at sampled free,
surface, and behind-surface points, while visible OBBs supervise centerness,
class, and box geometry @EFM3D-straub2024. These uses establish label
provenance; the information source determines actor observability.

For ARIA-NBV, the scene mesh #symb.ase.mesh supports candidate rendering, and
the target crop #symb.ase.mesh_target fixes the surface on which error is
measured. All-candidate depth #symb.oracle.depth_q and backprojected points
#symb.oracle.points_q instantiate the hypothetical observation associated with
each candidate. The resulting #symb.oracle.rri labels the consequence of an
action and becomes available only to the oracle.

A @ground-truth:short OBB defines oracle identity, pose, extent, crop, and target
bearing. Actor detection and association require an observation-derived
proposal. In a deployable protocol, that proposal defines the target hypothesis,
while ASE identity and geometry serve as matching and evaluation references.

The three states form a controlled augmentation chain:
#symb.rl.s_hist fixes logged evidence, #symb.rl.s_cf0 adds only factual selected
history, and #symb.rl.s_oracle adds counterfactual supervision. This ordering is
the conceptual data contract inherited by candidate generation and replay.

=== Visibility, Feasibility, and Utility

Three predicates apply to a candidate and answer different questions. *Visibility*
asks whether a view supplies evidence about a spatial element. *Feasibility*
asks whether the pose belongs to the admissible action set. *Utility* asks how
the target reconstruction changes after an admissible action. A candidate can
be physically feasible yet outside the local EFM3D volume, or it can frame the
target yet yield little reconstruction gain. These cases coexist because the
predicates refer to different structures.

Accordingly, #symb.rl.action_mask owns infeasibility, and reward is defined only
on the feasible action set. A feasible row may have negative gain. Oracle
evaluation can fail for a separate reason---for example, an unusable target crop
or render---in which case the label mask #symb.rl.q_label_mask is false while the
geometric reason code is unchanged. Keeping the masks distinct preserves the
difference between actions outside the feasible set and feasible actions lacking
an oracle training label.

Actor visibility is a property of the complete pipeline. It includes the scorer
tensor, the source of the target, the construction and masking of candidate
support, the selected observation used for the successor,
and the fields passed to the model. A scorer with actor-only tensors can still
depend indirectly on privileged support construction. Such a protocol supports
an oracle-assisted experiment. Claims about independently actor-constructed
actions require an actor-side proposal and feasibility path.
