#import "../../../shared/macros.typ": *
#import "../../../shared/symbols.typ": symb
#import "../../../shared/equations.typ": eqs

== State and Visibility Boundary

The learned component in this thesis is a masked finite-horizon candidate-value function: it predicts #symb.rl.qh values for a finite candidate table, and the decision rule selects among hard-valid rows. Training evidence is generated by offline, mesh-supervised counterfactual replay. @aria-synthetic-environments:short contributes both sensor-like logged streams and privileged ground truth; @egocentric-foundation-model-3d:short converts the logged subset into a local 3D representation, whereas depth, segmentation, @ground-truth:short boxes, meshes, counterfactual renders, and reconstruction labels remain supervision or evaluation channels @ProjectAria-ASE-2025 @EFM3D-straub2024. Storage in the same adapted snippet does not make these channels equally observable.

#figure(
  align(center, image(
    "../../figures/actor_oracle_boundary.pdf",
    width: 100%,
  )),
  caption: [Actor and oracle boundary. Legal #symb.rl.qh inputs are calibrated logged image evidence, poses, semi-dense geometry with uncertainty and observation support, frozen @egocentric-voxel-lifting:short features or predictions, an explicitly sourced target instruction, selected-view history, remaining budget, candidates, masks, and reason codes. @ground-truth:short depth, segmentation, boxes, meshes, target crops, counterfactual renders, labels, and endpoint evaluation remain privileged.],
) <fig:qh-actor-oracle-contract>

The visibility boundary is protocol-relative and temporal. A dense render for an unselected candidate at the current decision step is oracle evidence. A render from an already selected action may enter a later state only under an explicitly named source protocol: `CF-GT` for privileged mesh-rendered depth, `CF-sensor` for a declared sensor simulation, or V1 for an actor-visible observation. The same array shape can therefore denote different information, and source role must remain explicit.

=== ASE/EFM Logged Observation State

The target is treated as external task context, so the value is conceptually $Q(s_t,e,a)$ rather than a target-independent state value. The logged historic state contains the recorded trajectory evidence,

#block[#align(center)[#eqs.rl.s_hist]]

Each component of this tuple has a distinct information role:

*Calibrated multi-camera image snippets.* EFM3D consumes posed and calibrated RGB and greyscale Aria streams. For every stream and time step, EVL encodes the image with a frozen 2D foundation model, projects the centers of a local 3D voxel grid into the distorted camera model, bilinearly samples the feature maps inside the camera's valid radius, and aggregates the samples across cameras and time by their mean and standard deviation @EFM3D-straub2024. In the repository, `EfmCameraView` binds each normalized frame tensor to `CameraTW` calibration, device-clock timestamp, frame identifier, and an optional separately timestamped distance map. The ASE distance map is @ground-truth:short and remains oracle-only @ProjectAria-ASE-2025. Thus #symb.obs.img_rgb in #symb.rl.s_hist denotes calibrated, time-indexed image evidence; the concrete adapted snippet also carries left and right greyscale SLAM streams rather than a single unposed RGB tensor.

*Trajectory, calibration, and gravity.* The adapted trajectory is a timestamped sequence of world-from-rig `PoseTW` transforms with a world-frame gravity vector. EFM3D uses the most recent RGB rig pose, gravity-aligns its rotation, and places a local voxel grid in front of the rig; the per-camera calibration and poses then define the 3D-to-image sampling map @EFM3D-straub2024. These fields therefore determine the spatial registration, metric scale, gravity direction, and temporal alignment of all lifted evidence. They are also the basis for expressing a candidate relative to the current rig rather than learning values from arbitrary world coordinates.

*Semi-dense geometry and observation support.* ASE provides MPS-style world-frame semi-dense points, per-point distance and inverse-distance uncertainty, timestamps, and point-to-image observation records @ProjectAria-ASE-2025. The local `EfmPointsView` preserves padded per-time point slices, valid lengths, metric uncertainty, timestamps, and spatial bounds. EFM3D voxelizes the points into a binary surface mask and uses their observing camera centers to sample the rays before each surface point into a separate free-space mask @EFM3D-straub2024. Consequently, #symb.obs.points_semi alone denotes sparse surface support; free-space evidence is justified only when observation lineage and camera poses are retained. A missing point is not evidence that a voxel is free.

*Derived EVL field and heads.* EVL concatenates the lifted image features with the semi-dense surface and free-space masks, processes the volume with a 3D U-Net, and applies task heads for occupancy and 3D OBB detection. The paper's detection head predicts voxel centerness, class scores, and gravity-aligned box geometry; its surface head predicts occupancy and is supervised from @ground-truth:short depth samples labelled as free, surface, or occupied @EFM3D-straub2024. The resulting #symb.vin.field_v is therefore a learned, locally supported statistic of the logged snippet, not another raw sensor modality. The reported EFM3D configuration uses a finite $4 "m" times 4 "m" times 4 "m"$ grid anchored at the latest rig pose, so an out-of-extent target or candidate has missing EVL support rather than a measured zero or an invalid pose @EFM3D-straub2024.

The remaining tuple elements are decision context rather than ASE/EFM sensing modalities. #symb.rl.target identifies the entity whose reconstruction is valued, and #symb.rl.budget conditions the return on the remaining acquisition budget. The current V0 target values are derived from a selected @ground-truth:short box; a V1 target must instead come from EVL predictions or another actor-visible association path. This provenance distinction is consistent with `EfmSnippetView`, which exposes camera/calibration, trajectory, and semi-dense fields as actor observations while keeping `ARIA_OBB_PADDED`, nested `gt_data`, and attached ASE meshes on the oracle/evaluation side.

=== Counterfactual Actor State

The counterfactual actor state retains the immutable logged substrate and adds only information causally available after selected actions,

#block[#align(center)[#eqs.rl.s_cf0]]

For the canonical model, this compact tuple is read together with the explicit ordered selected-view history:

$
  s_t^"actor" = (s_t^"cf0", bold(H)_t)
$

In #symb.rl.s_cf0, the root EVL field remains fixed, whereas the accumulated point set $cal(P)_t$ may grow with selected observations. The finite candidate table #symb.oracle.candidates_t contains poses and generator provenance, not observations from those poses. #symb.rl.validity_mask defines the admissible action set, #symb.rl.invalid_reason records constraint failures, and the ordered history $bold(H)_t$ retains the selected approach sequence.

The richer geometry-updated state makes the selected observation channels explicit:

#block[#align(center)[#eqs.rl.s_cf_geom]]

In the current `CF-GT` protocol, selected #symb.obs.depth is rendered from #symb.ase.mesh and paired with a validity mask and candidate-camera calibration. Backprojection yields selected-view surface points #symb.obs.points_cf; the corresponding camera-to-surface rays delimit observed free space, and #symb.obs.face_normal records local surface orientation. These quantities form a geometry-only successor observation. They do not contain the RGB or greyscale images required by EFM3D's 2D feature encoder and therefore cannot support a fresh EVL field at the selected pose @EFM3D-straub2024.

The transition from $t$ to $t+1$ may use only the observation produced by the selected row $a_t$. It may fuse its surface and ray evidence and update support, uncertainty, direction, and recency. It may not attach image features, detections, or EVL descriptors unless the protocol also provides the calibrated camera streams from which EFM3D derives them. Counterfactual geometry must therefore retain a source role and explicit absence masks for unavailable image-derived channels.

The counterfactual state is thus an *information state* for decision making, not automatically a complete Markov state of the physical scene. It becomes task-sufficient only if its retained root context, causal dynamic evidence, explicit history, target context, action support, and budget preserve every distinction needed to predict future target-specific return. A pose-only implementation updates #symb.rl.candidate_table, $bold(H)_t$, and #symb.rl.budget without acquiring new scene evidence; it is therefore a deliberately weaker `S0-pose` baseline rather than a realization of the geometry-updated state.

=== Privileged Oracle State

The oracle state adds complete or counterfactual quantities outside the actor input graph:

#block[#align(center)[#eqs.rl.s_oracle]]

#block[#align(center)[#eqs.rl.nbv_process_tuple]]

ASE provides per-frame metric @ground-truth:short depth aligned with RGB, per-pixel instance identifiers, class mappings, and the scene trajectory; the EFM3D release adds ASE OBB metadata and validation meshes for object-detection and surface-reconstruction supervision @ProjectAria-ASE-2025 @EFM3D-straub2024. EFM3D uses the depth channel to supervise occupancy at sampled free, surface, and behind-surface points, while visible OBBs supervise centerness, class, and box geometry @EFM3D-straub2024. These uses establish label provenance, not actor observability.

For ARIA-NBV, #symb.ase.mesh is the privileged reference surface used for candidate rendering and reconstruction evaluation, while #symb.ase.mesh_target fixes the selected entity's evaluation support. All-candidate depth #symb.oracle.depth_q and backprojected point sets #symb.oracle.points_q answer counterfactual queries for unselected rows. #symb.oracle.rri then compares target reconstruction error before and after adding that candidate evidence. Depth, points, crops, and RRI are legal for label generation, oracle search, diagnostics, and named upper bounds; none is a contemporaneous input to the student value model.

A @ground-truth:short OBB may define V0 identity, pose, extent, crop, and target-bearing instruction. It does not show that the actor detected or associated that object. V1 must obtain the target hypothesis from EVL predictions or another observation-derived path, retaining ASE identity, segmentation, OBBs, and meshes only for matching and evaluation.

The state hierarchy therefore separates *what was logged*, *what a selected counterfactual history may causally add*, and *what only the oracle can know*. Its layers are related by controlled information projections, not by freely copying arrays between stores. In particular, an oracle tensor may be persisted beside actor tensors for efficient replay without becoming part of the actor state.

=== Visibility, Feasibility, and Utility

Visibility answers whether a modality contains evidence for a spatial element from a particular view; feasibility answers whether an action is admissible; utility answers how beneficial an admissible action is for the target. These concepts must not be collapsed. A target can be weakly visible from a geometrically valid candidate, a candidate can lie outside EVL support while remaining physically reachable, and an oracle render can fail even though the candidate pose itself is feasible.

Invalidity is a constraint rather than a reward value. Geometry-invalid candidates receive a hard action mask and a persisted candidate reason code before policy selection, stochastic normalization, loss construction, and bootstrap maximization. A geometrically feasible candidate may still have low or negative target gain. Failure of the separate oracle evaluation does not create a candidate reason code: depending on the configured recipe, the affected row or table is skipped, or its `oracle_label_mask` and `q_train_mask` are cleared and the oracle failure is reported separately. Oracle-derived feasibility must be distinguished from a deployable validity estimate whenever policy claims cross from V0 to V1.
