"""Target-conditioned replay transitions and persisted rollout stores.

`aria_nbv.rollouts` owns the multi-step thesis replay and persistence surface.
Operational rollout-dataset generation lives in `aria_nbv.oracle.pipelines`;
raw snippet access and immutable VIN offline stores remain in
`aria_nbv.data_handling`.
"""

from .counterfactuals import (
    CounterfactualCandidateEvaluation,
    CounterfactualEvaluatorFn,
    CounterfactualMetricBundle,
    CounterfactualPoseGenerator,
    CounterfactualPoseGeneratorConfig,
    CounterfactualRolloutResult,
    CounterfactualSelectionPolicy,
    CounterfactualSelectionRecord,
    CounterfactualStepResult,
    CounterfactualTrajectory,
)
from .inspection import (
    RolloutSuspiciousQueryConfig,
    candidate_audit_rows,
    candidate_group_summary_rows,
    candidate_result_diagnostic_counts,
    decode_invalid_reason,
    decode_position_id,
    decode_strategy_id,
    decode_target_invalid_reason,
    discover_rollout_store_paths,
    rollout_step_objective_rows,
    rollout_store_inventory_rows,
    rollout_tree_summary_rows,
    selected_depth_preview,
    selected_depth_summary_rows,
    suspicious_rollout_rows,
    target_audit_rows,
    validity_waterfall_rows,
)
from .manifest import (
    ROLLOUT_MANIFEST_FILENAME,
    ROLLOUT_MANIFEST_VERSION,
    RolloutStoreInvocation,
    RolloutStoreManifestContext,
)
from .shard_manifest import (
    ROLLOUT_SHARD_MANIFEST_VERSION,
    ROLLOUT_SHARD_OWNER_FILENAME,
    ROLLOUT_SHARD_SUCCESS_FILENAME,
    RolloutShardEntry,
    RolloutShardRow,
)
from .target_counterfactuals import (
    SCENE_CROP_POLICY_SNIPPET_EXTENT_V1,
    TARGET_CROP_POLICY_GT_OBB_ORIENTED_ANY_VERTEX_V1,
    CounterfactualTargetOracleRriScorer,
    CounterfactualTargetOracleRriScorerConfig,
    TargetRriInvalidError,
)
from .trace import (
    INVALID_REASON_CODES,
    INVALID_REASON_VERSION,
    RolloutLineage,
    RolloutZarrRecord,
)
from .zarr_store import (
    DEFAULT_RETURN_SEMANTICS,
    ROLLOUT_ZARR_SCHEMA_ID,
    ROLLOUT_ZARR_SCHEMA_VERSION,
    RolloutZarrStoreConfig,
    RolloutZarrStoreReader,
    RolloutZarrValidationResult,
    RolloutZarrWriteResult,
    validate_rollout_zarr_store,
    write_rollout_zarr_store,
)

__all__ = [
    "DEFAULT_RETURN_SEMANTICS",
    "INVALID_REASON_CODES",
    "INVALID_REASON_VERSION",
    "ROLLOUT_ZARR_SCHEMA_ID",
    "ROLLOUT_ZARR_SCHEMA_VERSION",
    "ROLLOUT_MANIFEST_FILENAME",
    "ROLLOUT_MANIFEST_VERSION",
    "ROLLOUT_SHARD_MANIFEST_VERSION",
    "ROLLOUT_SHARD_OWNER_FILENAME",
    "ROLLOUT_SHARD_SUCCESS_FILENAME",
    "SCENE_CROP_POLICY_SNIPPET_EXTENT_V1",
    "TARGET_CROP_POLICY_GT_OBB_ORIENTED_ANY_VERTEX_V1",
    "CounterfactualCandidateEvaluation",
    "CounterfactualEvaluatorFn",
    "CounterfactualMetricBundle",
    "CounterfactualPoseGenerator",
    "CounterfactualPoseGeneratorConfig",
    "CounterfactualRolloutResult",
    "CounterfactualSelectionPolicy",
    "CounterfactualSelectionRecord",
    "CounterfactualStepResult",
    "CounterfactualTargetOracleRriScorer",
    "CounterfactualTargetOracleRriScorerConfig",
    "CounterfactualTrajectory",
    "TargetRriInvalidError",
    "RolloutLineage",
    "RolloutSuspiciousQueryConfig",
    "RolloutShardEntry",
    "RolloutShardRow",
    "RolloutStoreInvocation",
    "RolloutStoreManifestContext",
    "RolloutZarrStoreConfig",
    "RolloutZarrStoreReader",
    "RolloutZarrRecord",
    "RolloutZarrValidationResult",
    "RolloutZarrWriteResult",
    "candidate_audit_rows",
    "candidate_group_summary_rows",
    "candidate_result_diagnostic_counts",
    "decode_invalid_reason",
    "decode_position_id",
    "decode_strategy_id",
    "decode_target_invalid_reason",
    "discover_rollout_store_paths",
    "rollout_store_inventory_rows",
    "rollout_step_objective_rows",
    "rollout_tree_summary_rows",
    "selected_depth_preview",
    "selected_depth_summary_rows",
    "suspicious_rollout_rows",
    "target_audit_rows",
    "validity_waterfall_rows",
    "validate_rollout_zarr_store",
    "write_rollout_zarr_store",
]
