// Generated by scripts/thesis_prune_audit.py; edit prune_targets.typ.
#import "draft_markers.typ": prune_target

#heading(numbering: none, outlined: false)[Prune targets (development review)]
#text(size: 8.5pt, fill: gray)[These are evidence-backed review targets, not canonical-definition deletions. Static counts exclude registry definitions; the current reader-facing build does not expose a per-term runtime count.]

#prune_target([ADT], key: "glossary.aria-digital-twin", reason: "trivial common terminology", static_occurrences: 0, build_occurrences: "not available")
#prune_target([AEO], key: "glossary.aria-everyday-objects", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([AUC], key: "glossary.area-under-curve", reason: "trivial common terminology", static_occurrences: 0, build_occurrences: "not available")
#prune_target([CPF], key: "glossary.central-pupil-frame", reason: "unreferenced implementation detail", static_occurrences: 0, build_occurrences: "not available")
#prune_target([DoF], key: "glossary.degrees-of-freedom", reason: "trivial common terminology", static_occurrences: 0, build_occurrences: "not available")
#prune_target([5DoF], key: "glossary.five-degrees-of-freedom", reason: "duplicate/alias", static_occurrences: 0, build_occurrences: "not available")
#prune_target([6DoF], key: "glossary.six-degrees-of-freedom", reason: "duplicate/alias", static_occurrences: 0, build_occurrences: "not available")
#prune_target([LUF], key: "glossary.left-up-forward", reason: "unreferenced implementation detail", static_occurrences: 0, build_occurrences: "not available")
#prune_target([MPS], key: "glossary.machine-perception-services", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([MTD], key: "glossary.motion-trajectory-data", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([MFCD], key: "glossary.multi-frame-camera-data", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([MSDPD], key: "glossary.multi-semi-dense-point-data", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([MVS], key: "glossary.multi-view-stereo", reason: "trivial common terminology", static_occurrences: 0, build_occurrences: "not available")
#prune_target([SSL], key: "glossary.scene-script-language", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([SLAM], key: "glossary.simultaneous-localization-and-mapping", reason: "trivial common terminology", static_occurrences: 0, build_occurrences: "not available")
#prune_target([3DGS], key: "glossary.three-dimensional-gaussian-splatting", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([VRS], key: "glossary.virtual-reality-standard", reason: "only needed by another document", static_occurrences: 0, build_occurrences: "not available")
#prune_target([VIO], key: "glossary.visual-inertial-odometry", reason: "trivial common terminology", static_occurrences: 0, build_occurrences: "not available")
