#import "../../shared/symbols.typ": symb

= Discussion <sec:thesis-discussion>

The current evidence supports a narrow implementation conclusion. ARIA-NBV has an executable finite-candidate path that separates actor-visible policy inputs from oracle-only target geometry, applies invalidity as a hard decision constraint, evaluates target-specific reconstruction change offline, and exposes the resulting store through one typed reporting seam. This establishes that the proposed experiment can be represented and audited; it does not establish that one candidate family, rollout policy, or learned model performs better than another.

The rollout attempts also expose a concrete systems limitation. Counterfactual scoring repeatedly renders a large mesh for a candidate set, so renderer memory and latency constrain the feasible branch factor and rollout volume before statistical efficiency becomes relevant. The observed out-of-memory failure is diagnostic evidence for batching and resource measurement, not evidence about the candidate distribution or planning objective. A completed pair of validated stores is required before throughput, storage, or failure rates can be generalized even to the configured training-source pilot.

The scientific limitations are more restrictive. The current attempts use training sources, the default JSON bundle is a schema fixture, and no held-out paired policy table supports the endpoint estimand. Metric repeatability and a meaningful-headroom gate have not yet been established, while the learned finite-horizon #symb.rl.qh comparison remains downstream of those checks. Accordingly, the thesis cannot yet distinguish negligible oracle headroom from inadequate candidate support, insufficient rollout coverage, target observability, or learned-control failure.

The next evidential step is procedural rather than architectural: complete validated stores under resolved manifests, freeze the eligible population and exclusions, establish oracle stability, and only then run matched held-out policy comparisons. Additional representations, continuous control, or semantic planners would address different hypotheses and are not justified by the present readiness evidence.
