"""Metric computation modules for RRI labels and rollout evaluation."""

from .multi_step import (
    CandidateOrderConsistency,
    CandidatePathIncrementStats,
    CandidatePrimaryInvalidReasonStats,
    SelectedActionOracleComparison,
    TorchRolloutMetrics,
    candidate_best_value,
    candidate_masked_mean,
    candidate_order_consistency,
    candidate_path_increment_stats,
    candidate_policy_entropy,
    candidate_primary_invalid_reason_share,
    candidate_provenance_share,
    candidate_topk_oracle_hit,
    discounted_selected_return,
    endpoint_log_gain_tensor,
    endpoint_target_gain_tensor,
    selected_action_oracle_comparison,
    selected_path_length_tensor,
    summarize_selected_rollout_tensors,
)
from .multi_step_tables import (
    TargetRolloutMetricSummary,
    endpoint_log_gain,
    endpoint_target_gain,
    finite_horizon_target_return,
    selected_target_reward,
    selected_target_rri,
    summarize_target_rollout_metrics,
    target_point_mesh_error_after,
    target_point_mesh_error_before,
)
from .point_mesh import chamfer_point_mesh, chamfer_point_mesh_batched
from .single_step import topk_accuracy_from_probs
from .torchmetrics_multi import (
    CandidateOrderConsistencyMetric,
    CandidatePathIncrementMetric,
    CandidatePolicyEntropyMetric,
    CandidatePrimaryInvalidReasonMetric,
    CandidateProvenanceShareMetric,
    CandidateTableMetrics,
    CandidateTopKOracleHitMetric,
    FiniteMeanMetric,
    SelectedActionOracleComparisonMetric,
    SelectedPathCostMetrics,
    SelectedRolloutMetrics,
)
from .torchmetrics_single import LabelHistogram, RriErrorStats, VinMetrics, VinMetricsConfig

__all__ = [
    "CandidateOrderConsistency",
    "CandidateOrderConsistencyMetric",
    "CandidatePathIncrementMetric",
    "CandidatePathIncrementStats",
    "CandidatePolicyEntropyMetric",
    "CandidatePrimaryInvalidReasonMetric",
    "CandidatePrimaryInvalidReasonStats",
    "CandidateProvenanceShareMetric",
    "CandidateTableMetrics",
    "CandidateTopKOracleHitMetric",
    "FiniteMeanMetric",
    "LabelHistogram",
    "RriErrorStats",
    "SelectedActionOracleComparison",
    "SelectedActionOracleComparisonMetric",
    "SelectedPathCostMetrics",
    "SelectedRolloutMetrics",
    "TargetRolloutMetricSummary",
    "TorchRolloutMetrics",
    "VinMetrics",
    "VinMetricsConfig",
    "candidate_best_value",
    "candidate_masked_mean",
    "candidate_order_consistency",
    "candidate_path_increment_stats",
    "candidate_policy_entropy",
    "candidate_primary_invalid_reason_share",
    "candidate_provenance_share",
    "candidate_topk_oracle_hit",
    "chamfer_point_mesh",
    "chamfer_point_mesh_batched",
    "discounted_selected_return",
    "endpoint_log_gain",
    "endpoint_log_gain_tensor",
    "endpoint_target_gain",
    "endpoint_target_gain_tensor",
    "finite_horizon_target_return",
    "selected_action_oracle_comparison",
    "selected_path_length_tensor",
    "selected_target_reward",
    "selected_target_rri",
    "summarize_selected_rollout_tensors",
    "summarize_target_rollout_metrics",
    "target_point_mesh_error_after",
    "target_point_mesh_error_before",
    "topk_accuracy_from_probs",
]
