#!/usr/bin/env python3
"""Generate a compact static dependency diagram for the public API reference."""

from __future__ import annotations

import ast
import json
from collections import defaultdict
from pathlib import Path

try:  # Direct execution puts ``scripts/`` on sys.path; pytest imports the package.
    from quartodoc_expand_config import PACKAGE_ROOT, discover_modules
except ModuleNotFoundError:  # pragma: no cover - exercised by the pytest import path.
    from scripts.quartodoc_expand_config import PACKAGE_ROOT, discover_modules

REPO_ROOT = Path(__file__).resolve().parents[1]
REFERENCE_DIR = REPO_ROOT / "docs" / "reference"
DIAGRAM_PATH = REFERENCE_DIR / "_package_dependencies.mmd"
DATA_PATH = REFERENCE_DIR / "_package_dependencies.json"
MAX_EDGES = 15


def module_name(path: Path) -> str:
    relative = path.relative_to(PACKAGE_ROOT)
    if path.name == "__init__.py":
        return ".".join(relative.parent.parts)
    return ".".join(relative.with_suffix("").parts)


def resolve_relative_import(path: Path, node: ast.ImportFrom) -> str | None:
    if node.level == 0:
        return node.module

    base = list(path.relative_to(PACKAGE_ROOT).parent.parts)
    if node.level > 1:
        base = base[: 1 - node.level]
    if node.module:
        base.extend(node.module.split("."))
    return ".".join(base) or None


def import_targets(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    targets: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            targets.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            target = resolve_relative_import(path, node)
            if target:
                targets.add(target)
    return targets


def public_top_level_packages() -> list[str]:
    return [
        name
        for name, is_package in discover_modules()
        if is_package and "." not in name
    ]


def static_dependencies(packages: set[str]) -> dict[tuple[str, str], set[str]]:
    dependencies: dict[tuple[str, str], set[str]] = defaultdict(set)
    for path in PACKAGE_ROOT.rglob("*.py"):
        source_module = module_name(path)
        if not source_module or source_module.split(".")[0] not in packages:
            continue
        source_package = source_module.split(".")[0]
        for target_module in import_targets(path):
            target_parts = target_module.split(".")
            if target_parts[0] == "aria_nbv":
                target_parts = target_parts[1:]
            if not target_parts or target_parts[0] not in packages:
                continue
            target_package = target_parts[0]
            if source_package != target_package:
                dependencies[(source_package, target_package)].add(source_module)
    return dependencies


def render_mermaid(packages: list[str], edges: list[tuple[str, str, int]]) -> str:
    lines = [
        "%% Generated by scripts/quartodoc_generate_dependency_diagram.py; do not edit.",
        "flowchart LR",
    ]
    for package in packages:
        lines.append(f'  {package}["{package}"]')
    for source, target, count in edges:
        lines.append(f'  {source} -->|"{count}"| {target}')
    lines.extend(
        [
            "",
            "  classDef input fill:#D5E8D4,stroke:#82B366,color:#17202A,stroke-width:1.5px,rx:0,ry:0;",
            "  classDef output fill:#F8CECC,stroke:#B85450,color:#17202A,stroke-width:1.5px,rx:0,ry:0;",
            "  classDef compute fill:#E1D5E7,stroke:#9673A6,color:#17202A,stroke-width:1.5px,rx:8,ry:8;",
            "  classDef data fill:#F5F5F5,stroke:#9E9E9E,color:#17202A,stroke-width:1.2px,rx:0,ry:0;",
            "  classDef package fill:#E1D5E7,stroke:#9673A6,color:#17202A,stroke-width:1.5px,rx:6,ry:6;",
            f"  class {','.join(packages)} package;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    packages = public_top_level_packages()
    package_set = set(packages)
    dependencies = static_dependencies(package_set)
    edges = sorted(
        (
            (source, target, len(importers))
            for (source, target), importers in dependencies.items()
        ),
        key=lambda edge: (-edge[2], edge[0], edge[1]),
    )[:MAX_EDGES]
    DIAGRAM_PATH.write_text(render_mermaid(packages, edges), encoding="utf-8")
    DATA_PATH.write_text(
        json.dumps(
            {
                "description": "Static cross-package imports, collapsed to public top-level packages.",
                "packages": packages,
                "edges": [
                    {"source": source, "target": target, "importing_modules": count}
                    for source, target, count in edges
                ],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
