#import "../../../shared/macros.typ": *
#import "../../../shared/symbols.typ": symb

== Actor State and Representation Boundary <sec:thesis-scene-representation>

// implementation: targets/descriptor.py; vin/candidate_scorer.py; rollouts/replay/state.py; rollouts/replay/engine.py
The implemented one-step scorer consumes an actor-visible snippet view, a row-aligned set of candidate camera poses, a reference rig pose, calibrated candidate cameras, and optionally cached @egocentric-voxel-lifting:short output. Its scene carrier is therefore the typed EFM/VIN snippet rather than a proposed universal map. The carrier provides logged camera and trajectory data, semi-dense geometry, and the EFM3D features used by the current VIN architecture. Candidate-conditioned projections and shared scene tokens are derived from these inputs; oracle @relative-reconstruction-improvement:short labels enter the loss after prediction and are not scorer inputs.

Target-conditioned candidate generation receives a narrower instruction. The implemented target descriptor contains the semantic class identifier and name, the target pose and positive metric extents, and the target pose relative to the snippet reference frame. It also derives a stable identifier from those sanitized fields. This descriptor may be constructed from ground truth in the V0 oracle task, but it excludes source rows, match diagnostics, target crops, gains, invalidity, and rollout-storage details. Ground-truth provenance must therefore be reported at the task level even though the object passed into the generator is actor-safe in shape.

The rollout state is smaller still. An in-memory transition stores the full candidate result, the selected valid and shell indices, selection scores and probabilities, the selection policy, and the root-to-selected pose chain. Candidate regeneration at the next step uses the selected pose, pose history, remaining budget, the scene mesh needed by the current oracle generator, and the same target instruction. It does not update an implemented persistent neural scene memory after each action. The replay artifact may retain a mesh-rendered selected-depth map for reconstructing successor history, but this map is privileged counterfactual evidence generated from the GT mesh, not a deployable RGB-D observation.

These implemented carriers impose three non-negotiable boundaries. First, invalidity is represented by the hard candidate mask and versioned reason codes rather than by a small score. Second, actor and oracle fields remain separate: GT meshes, candidate renders, target crops, target errors, and returns supervise generation or evaluation only. Third, row and frame semantics are explicit. Candidate rows stay aligned to stable shell indices, while the stored world and root-relative poses permit readers to construct local geometric features without treating the arbitrary world origin as information.

The current system does not yet provide a learned target token, a fused occupied/free/unknown memory, DINO-on-point features, directional visibility memory, target-centred EVL re-lifting, or a renderable 3D Gaussian actor state. Those representations remain plausible extensions, but they are not part of the method evaluated here. This restriction keeps the finite-horizon question identifiable: before comparing richer encoders, the project must first train and validate a value model over the replay fields that already exist.
