-- Generated by scripts/glossary_build.py; edit docs/typst/shared/glossary.typ.

return {
  ["acquisition-cost"] = {
    label = "Acquisition Cost",
    short = "cost",
    anchor = "term-acquisition-cost",
  },
  ["area-under-curve"] = {
    label = "Area Under Curve",
    short = "AUC",
    anchor = "term-area-under-curve",
  },
  ["aria-digital-twin"] = {
    label = "Aria Digital Twin",
    short = "ADT",
    anchor = "term-aria-digital-twin",
  },
  ["aria-everyday-objects"] = {
    label = "Aria Everyday Objects",
    short = "AEO",
    anchor = "term-aria-everyday-objects",
  },
  ["aria-synthetic-environments"] = {
    label = "Aria Synthetic Environments",
    short = "ASE",
    anchor = "term-aria-synthetic-environments",
  },
  ["candidate-view"] = {
    label = "Candidate View",
    short = "candidate",
    anchor = "term-candidate-view",
  },
  ["central-pupil-frame"] = {
    label = "Central Pupil Frame",
    short = "CPF",
    anchor = "term-central-pupil-frame",
  },
  ["chamfer-distance"] = {
    label = "Chamfer Distance",
    short = "CD",
    anchor = "term-chamfer-distance",
  },
  ["counterfactual-transition"] = {
    label = "Counterfactual Transition",
    short = "transition",
    anchor = "term-counterfactual-transition",
  },
  ["coverage-ratio"] = {
    label = "Coverage Ratio",
    short = "CR",
    anchor = "term-coverage-ratio",
  },
  ["degrees-of-freedom"] = {
    label = "Degrees of Freedom",
    short = "DoF",
    anchor = "term-degrees-of-freedom",
  },
  ["egocentric-foundation-model-3d"] = {
    label = "Egocentric Foundation Model 3D",
    short = "EFM3D",
    anchor = "term-egocentric-foundation-model-3d",
  },
  ["egocentric-voxel-lifting"] = {
    label = "Egocentric Voxel Lifting",
    short = "EVL",
    anchor = "term-egocentric-voxel-lifting",
  },
  ["finite-candidate-action-set"] = {
    label = "Finite Candidate Action Set",
    short = "action set",
    anchor = "term-finite-candidate-action-set",
  },
  ["finite-horizon-q-function"] = {
    label = "Finite-Horizon Q Function",
    short = "Q_H",
    anchor = "term-finite-horizon-q-function",
  },
  ["finite-horizon-return"] = {
    label = "Finite-Horizon Return",
    short = "return",
    anchor = "term-finite-horizon-return",
  },
  ["five-degrees-of-freedom"] = {
    label = "Five Degrees of Freedom",
    short = "5DoF",
    anchor = "term-five-degrees-of-freedom",
  },
  ["frustum"] = {
    label = "Frustum",
    short = "frustum",
    anchor = "term-frustum",
  },
  ["geometry-rich-counterfactual-state"] = {
    label = "Geometry-Rich Counterfactual State",
    short = "CF+ state",
    anchor = "term-geometry-rich-counterfactual-state",
  },
  ["ground-truth"] = {
    label = "Ground Truth",
    short = "GT",
    anchor = "term-ground-truth",
  },
  ["ground-truth-target-evaluation"] = {
    label = "Ground-Truth Target Evaluation",
    short = "GT-EVAL",
    anchor = "term-ground-truth-target-evaluation",
  },
  ["historic-snippet-state"] = {
    label = "Historic Snippet State",
    short = "historic state",
    anchor = "term-historic-snippet-state",
  },
  ["left-up-forward"] = {
    label = "Left-Up-Forward",
    short = "LUF",
    anchor = "term-left-up-forward",
  },
  ["machine-perception-services"] = {
    label = "Machine Perception Services",
    short = "MPS",
    anchor = "term-machine-perception-services",
  },
  ["minimal-counterfactual-state"] = {
    label = "Minimal Counterfactual Actor State",
    short = "CF0 state",
    anchor = "term-minimal-counterfactual-state",
  },
  ["motion-trajectory-data"] = {
    label = "Motion Trajectory Data",
    short = "MTD",
    anchor = "term-motion-trajectory-data",
  },
  ["multi-frame-camera-data"] = {
    label = "Multi-Frame Camera Data",
    short = "MFCD",
    anchor = "term-multi-frame-camera-data",
  },
  ["multi-semi-dense-point-data"] = {
    label = "Multi-Semi-Dense Point Data",
    short = "MSDPD",
    anchor = "term-multi-semi-dense-point-data",
  },
  ["multi-view-stereo"] = {
    label = "Multi-view Stereo",
    short = "MVS",
    anchor = "term-multi-view-stereo",
  },
  ["next-best-view"] = {
    label = "Next-Best-View",
    short = "NBV",
    anchor = "term-next-best-view",
  },
  ["observed-target-selection"] = {
    label = "Observed Target Selection",
    short = "OBS-SEL",
    anchor = "term-observed-target-selection",
  },
  ["occupancy-grid"] = {
    label = "Occupancy Grid",
    short = "Occupancy Grid",
    anchor = "term-occupancy-grid",
  },
  ["oracle-rollout-state"] = {
    label = "Oracle Rollout State",
    short = "oracle state",
    anchor = "term-oracle-rollout-state",
  },
  ["oracle-rri"] = {
    label = "Oracle RRI",
    short = "oracle RRI",
    anchor = "term-oracle-rri",
  },
  ["oriented-bounding-box"] = {
    label = "Oriented Bounding Box",
    short = "OBB",
    anchor = "term-oriented-bounding-box",
  },
  ["persisted-offline-state"] = {
    label = "Persisted Offline Sample State",
    short = "offline state",
    anchor = "term-persisted-offline-state",
  },
  ["point-cloud"] = {
    label = "Point Cloud",
    short = "PC",
    anchor = "term-point-cloud",
  },
  ["predicted-target-q"] = {
    label = "Predicted-Target Q",
    short = "PRED-Q",
    anchor = "term-predicted-target-q",
  },
  ["project-aria"] = {
    label = "Project Aria",
    short = "Project Aria",
    anchor = "term-project-aria",
  },
  ["relative-reconstruction-improvement"] = {
    label = "Relative Reconstruction Improvement",
    short = "RRI",
    anchor = "term-relative-reconstruction-improvement",
  },
  ["rollout-state"] = {
    label = "Rollout State",
    short = "state",
    anchor = "term-rollout-state",
  },
  ["scene-script-language"] = {
    label = "SceneScript Language",
    short = "SSL",
    anchor = "term-scene-script-language",
  },
  ["simultaneous-localization-and-mapping"] = {
    label = "Simultaneous Localization and Mapping",
    short = "SLAM",
    anchor = "term-simultaneous-localization-and-mapping",
  },
  ["six-degrees-of-freedom"] = {
    label = "Six Degrees of Freedom",
    short = "6DoF",
    anchor = "term-six-degrees-of-freedom",
  },
  ["snippet"] = {
    label = "Snippet",
    short = "snippet",
    anchor = "term-snippet",
  },
  ["target-conditioned-nbv-mdp"] = {
    label = "Target-Conditioned NBV MDP",
    short = "NBV MDP",
    anchor = "term-target-conditioned-nbv-mdp",
  },
  ["target-conditioned-scorer"] = {
    label = "Target-Conditioned Scorer",
    short = "target-conditioned scorer",
    anchor = "term-target-conditioned-scorer",
  },
  ["target-of-interest"] = {
    label = "Target of Interest",
    short = "target",
    anchor = "term-target-of-interest",
  },
  ["target-root-gain-reward"] = {
    label = "Target Root-Gain Reward",
    short = "reward",
    anchor = "term-target-root-gain-reward",
  },
  ["target-specific-rri"] = {
    label = "Target-Specific RRI",
    short = "target RRI",
    anchor = "term-target-specific-rri",
  },
  ["three-dimensional-gaussian-splatting"] = {
    label = "3D Gaussian Splatting",
    short = "3DGS",
    anchor = "term-three-dimensional-gaussian-splatting",
  },
  ["track"] = {
    label = "Track",
    short = "track",
    anchor = "term-track",
  },
  ["validity-mask"] = {
    label = "Validity Mask",
    short = "mask",
    anchor = "term-validity-mask",
  },
  ["view-introspection-network"] = {
    label = "View Introspection Network",
    short = "VIN",
    anchor = "term-view-introspection-network",
  },
  ["virtual-reality-standard"] = {
    label = "Virtual Reality Standard",
    short = "VRS",
    anchor = "term-virtual-reality-standard",
  },
  ["visual-inertial-odometry"] = {
    label = "Visual-Inertial Odometry",
    short = "VIO",
    anchor = "term-visual-inertial-odometry",
  },
}
